// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::ap_ST_fsm_state1 = "1";
const sc_lv<32> linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<14> linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::ap_const_lv14_2 = "10";
const bool linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::ap_const_boolean_1 = true;

linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_0_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_0_V_empty_n );

    SC_METHOD(thread_data_V_data_0_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_1_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_1_V_empty_n );

    SC_METHOD(thread_data_V_data_1_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_2_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_2_V_empty_n );

    SC_METHOD(thread_data_V_data_2_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_3_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_3_V_empty_n );

    SC_METHOD(thread_data_V_data_3_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_4_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_4_V_empty_n );

    SC_METHOD(thread_data_V_data_4_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_5_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_5_V_empty_n );

    SC_METHOD(thread_data_V_data_5_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_6_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_6_V_empty_n );

    SC_METHOD(thread_data_V_data_6_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_7_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_7_V_empty_n );

    SC_METHOD(thread_data_V_data_7_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_8_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_8_V_empty_n );

    SC_METHOD(thread_data_V_data_8_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_data_V_data_9_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_9_V_empty_n );

    SC_METHOD(thread_data_V_data_9_V_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_io_acc_block_signal_op25);
    sensitive << ( data_V_data_0_V_empty_n );
    sensitive << ( data_V_data_1_V_empty_n );
    sensitive << ( data_V_data_2_V_empty_n );
    sensitive << ( data_V_data_3_V_empty_n );
    sensitive << ( data_V_data_4_V_empty_n );
    sensitive << ( data_V_data_5_V_empty_n );
    sensitive << ( data_V_data_6_V_empty_n );
    sensitive << ( data_V_data_7_V_empty_n );
    sensitive << ( data_V_data_8_V_empty_n );
    sensitive << ( data_V_data_9_V_empty_n );

    SC_METHOD(thread_io_acc_block_signal_op46);
    sensitive << ( res_V_data_0_V_full_n );
    sensitive << ( res_V_data_1_V_full_n );
    sensitive << ( res_V_data_2_V_full_n );
    sensitive << ( res_V_data_3_V_full_n );
    sensitive << ( res_V_data_4_V_full_n );
    sensitive << ( res_V_data_5_V_full_n );
    sensitive << ( res_V_data_6_V_full_n );
    sensitive << ( res_V_data_7_V_full_n );
    sensitive << ( res_V_data_8_V_full_n );
    sensitive << ( res_V_data_9_V_full_n );

    SC_METHOD(thread_res_V_data_0_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_0_V_full_n );

    SC_METHOD(thread_res_V_data_0_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_0_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_0_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_1_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_1_V_full_n );

    SC_METHOD(thread_res_V_data_1_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_1_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_1_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_2_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_2_V_full_n );

    SC_METHOD(thread_res_V_data_2_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_2_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_2_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_3_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_3_V_full_n );

    SC_METHOD(thread_res_V_data_3_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_3_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_3_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_4_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_4_V_full_n );

    SC_METHOD(thread_res_V_data_4_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_4_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_4_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_5_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_5_V_full_n );

    SC_METHOD(thread_res_V_data_5_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_5_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_5_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_6_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_6_V_full_n );

    SC_METHOD(thread_res_V_data_6_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_6_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_6_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_7_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_7_V_full_n );

    SC_METHOD(thread_res_V_data_7_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_7_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_7_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_8_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_8_V_full_n );

    SC_METHOD(thread_res_V_data_8_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_8_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_8_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_9_V_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( res_V_data_9_V_full_n );

    SC_METHOD(thread_res_V_data_9_V_din);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( data_V_data_9_V_dout );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_res_V_data_9_V_write);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( io_acc_block_signal_op25 );
    sensitive << ( io_acc_block_signal_op46 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_data_0_V_dout, "(port)data_V_data_0_V_dout");
    sc_trace(mVcdFile, data_V_data_0_V_empty_n, "(port)data_V_data_0_V_empty_n");
    sc_trace(mVcdFile, data_V_data_0_V_read, "(port)data_V_data_0_V_read");
    sc_trace(mVcdFile, data_V_data_1_V_dout, "(port)data_V_data_1_V_dout");
    sc_trace(mVcdFile, data_V_data_1_V_empty_n, "(port)data_V_data_1_V_empty_n");
    sc_trace(mVcdFile, data_V_data_1_V_read, "(port)data_V_data_1_V_read");
    sc_trace(mVcdFile, data_V_data_2_V_dout, "(port)data_V_data_2_V_dout");
    sc_trace(mVcdFile, data_V_data_2_V_empty_n, "(port)data_V_data_2_V_empty_n");
    sc_trace(mVcdFile, data_V_data_2_V_read, "(port)data_V_data_2_V_read");
    sc_trace(mVcdFile, data_V_data_3_V_dout, "(port)data_V_data_3_V_dout");
    sc_trace(mVcdFile, data_V_data_3_V_empty_n, "(port)data_V_data_3_V_empty_n");
    sc_trace(mVcdFile, data_V_data_3_V_read, "(port)data_V_data_3_V_read");
    sc_trace(mVcdFile, data_V_data_4_V_dout, "(port)data_V_data_4_V_dout");
    sc_trace(mVcdFile, data_V_data_4_V_empty_n, "(port)data_V_data_4_V_empty_n");
    sc_trace(mVcdFile, data_V_data_4_V_read, "(port)data_V_data_4_V_read");
    sc_trace(mVcdFile, data_V_data_5_V_dout, "(port)data_V_data_5_V_dout");
    sc_trace(mVcdFile, data_V_data_5_V_empty_n, "(port)data_V_data_5_V_empty_n");
    sc_trace(mVcdFile, data_V_data_5_V_read, "(port)data_V_data_5_V_read");
    sc_trace(mVcdFile, data_V_data_6_V_dout, "(port)data_V_data_6_V_dout");
    sc_trace(mVcdFile, data_V_data_6_V_empty_n, "(port)data_V_data_6_V_empty_n");
    sc_trace(mVcdFile, data_V_data_6_V_read, "(port)data_V_data_6_V_read");
    sc_trace(mVcdFile, data_V_data_7_V_dout, "(port)data_V_data_7_V_dout");
    sc_trace(mVcdFile, data_V_data_7_V_empty_n, "(port)data_V_data_7_V_empty_n");
    sc_trace(mVcdFile, data_V_data_7_V_read, "(port)data_V_data_7_V_read");
    sc_trace(mVcdFile, data_V_data_8_V_dout, "(port)data_V_data_8_V_dout");
    sc_trace(mVcdFile, data_V_data_8_V_empty_n, "(port)data_V_data_8_V_empty_n");
    sc_trace(mVcdFile, data_V_data_8_V_read, "(port)data_V_data_8_V_read");
    sc_trace(mVcdFile, data_V_data_9_V_dout, "(port)data_V_data_9_V_dout");
    sc_trace(mVcdFile, data_V_data_9_V_empty_n, "(port)data_V_data_9_V_empty_n");
    sc_trace(mVcdFile, data_V_data_9_V_read, "(port)data_V_data_9_V_read");
    sc_trace(mVcdFile, res_V_data_0_V_din, "(port)res_V_data_0_V_din");
    sc_trace(mVcdFile, res_V_data_0_V_full_n, "(port)res_V_data_0_V_full_n");
    sc_trace(mVcdFile, res_V_data_0_V_write, "(port)res_V_data_0_V_write");
    sc_trace(mVcdFile, res_V_data_1_V_din, "(port)res_V_data_1_V_din");
    sc_trace(mVcdFile, res_V_data_1_V_full_n, "(port)res_V_data_1_V_full_n");
    sc_trace(mVcdFile, res_V_data_1_V_write, "(port)res_V_data_1_V_write");
    sc_trace(mVcdFile, res_V_data_2_V_din, "(port)res_V_data_2_V_din");
    sc_trace(mVcdFile, res_V_data_2_V_full_n, "(port)res_V_data_2_V_full_n");
    sc_trace(mVcdFile, res_V_data_2_V_write, "(port)res_V_data_2_V_write");
    sc_trace(mVcdFile, res_V_data_3_V_din, "(port)res_V_data_3_V_din");
    sc_trace(mVcdFile, res_V_data_3_V_full_n, "(port)res_V_data_3_V_full_n");
    sc_trace(mVcdFile, res_V_data_3_V_write, "(port)res_V_data_3_V_write");
    sc_trace(mVcdFile, res_V_data_4_V_din, "(port)res_V_data_4_V_din");
    sc_trace(mVcdFile, res_V_data_4_V_full_n, "(port)res_V_data_4_V_full_n");
    sc_trace(mVcdFile, res_V_data_4_V_write, "(port)res_V_data_4_V_write");
    sc_trace(mVcdFile, res_V_data_5_V_din, "(port)res_V_data_5_V_din");
    sc_trace(mVcdFile, res_V_data_5_V_full_n, "(port)res_V_data_5_V_full_n");
    sc_trace(mVcdFile, res_V_data_5_V_write, "(port)res_V_data_5_V_write");
    sc_trace(mVcdFile, res_V_data_6_V_din, "(port)res_V_data_6_V_din");
    sc_trace(mVcdFile, res_V_data_6_V_full_n, "(port)res_V_data_6_V_full_n");
    sc_trace(mVcdFile, res_V_data_6_V_write, "(port)res_V_data_6_V_write");
    sc_trace(mVcdFile, res_V_data_7_V_din, "(port)res_V_data_7_V_din");
    sc_trace(mVcdFile, res_V_data_7_V_full_n, "(port)res_V_data_7_V_full_n");
    sc_trace(mVcdFile, res_V_data_7_V_write, "(port)res_V_data_7_V_write");
    sc_trace(mVcdFile, res_V_data_8_V_din, "(port)res_V_data_8_V_din");
    sc_trace(mVcdFile, res_V_data_8_V_full_n, "(port)res_V_data_8_V_full_n");
    sc_trace(mVcdFile, res_V_data_8_V_write, "(port)res_V_data_8_V_write");
    sc_trace(mVcdFile, res_V_data_9_V_din, "(port)res_V_data_9_V_din");
    sc_trace(mVcdFile, res_V_data_9_V_full_n, "(port)res_V_data_9_V_full_n");
    sc_trace(mVcdFile, res_V_data_9_V_write, "(port)res_V_data_9_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, data_V_data_0_V_blk_n, "data_V_data_0_V_blk_n");
    sc_trace(mVcdFile, data_V_data_1_V_blk_n, "data_V_data_1_V_blk_n");
    sc_trace(mVcdFile, data_V_data_2_V_blk_n, "data_V_data_2_V_blk_n");
    sc_trace(mVcdFile, data_V_data_3_V_blk_n, "data_V_data_3_V_blk_n");
    sc_trace(mVcdFile, data_V_data_4_V_blk_n, "data_V_data_4_V_blk_n");
    sc_trace(mVcdFile, data_V_data_5_V_blk_n, "data_V_data_5_V_blk_n");
    sc_trace(mVcdFile, data_V_data_6_V_blk_n, "data_V_data_6_V_blk_n");
    sc_trace(mVcdFile, data_V_data_7_V_blk_n, "data_V_data_7_V_blk_n");
    sc_trace(mVcdFile, data_V_data_8_V_blk_n, "data_V_data_8_V_blk_n");
    sc_trace(mVcdFile, data_V_data_9_V_blk_n, "data_V_data_9_V_blk_n");
    sc_trace(mVcdFile, res_V_data_0_V_blk_n, "res_V_data_0_V_blk_n");
    sc_trace(mVcdFile, res_V_data_1_V_blk_n, "res_V_data_1_V_blk_n");
    sc_trace(mVcdFile, res_V_data_2_V_blk_n, "res_V_data_2_V_blk_n");
    sc_trace(mVcdFile, res_V_data_3_V_blk_n, "res_V_data_3_V_blk_n");
    sc_trace(mVcdFile, res_V_data_4_V_blk_n, "res_V_data_4_V_blk_n");
    sc_trace(mVcdFile, res_V_data_5_V_blk_n, "res_V_data_5_V_blk_n");
    sc_trace(mVcdFile, res_V_data_6_V_blk_n, "res_V_data_6_V_blk_n");
    sc_trace(mVcdFile, res_V_data_7_V_blk_n, "res_V_data_7_V_blk_n");
    sc_trace(mVcdFile, res_V_data_8_V_blk_n, "res_V_data_8_V_blk_n");
    sc_trace(mVcdFile, res_V_data_9_V_blk_n, "res_V_data_9_V_blk_n");
    sc_trace(mVcdFile, io_acc_block_signal_op25, "io_acc_block_signal_op25");
    sc_trace(mVcdFile, io_acc_block_signal_op46, "io_acc_block_signal_op46");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::~linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read()));
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n.read();
    } else {
        data_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_0_V_read = ap_const_logic_1;
    } else {
        data_V_data_0_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n.read();
    } else {
        data_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_1_V_read = ap_const_logic_1;
    } else {
        data_V_data_1_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n.read();
    } else {
        data_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_2_V_read = ap_const_logic_1;
    } else {
        data_V_data_2_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n.read();
    } else {
        data_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_3_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_3_V_read = ap_const_logic_1;
    } else {
        data_V_data_3_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_4_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_4_V_blk_n = data_V_data_4_V_empty_n.read();
    } else {
        data_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_4_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_4_V_read = ap_const_logic_1;
    } else {
        data_V_data_4_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_5_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_5_V_blk_n = data_V_data_5_V_empty_n.read();
    } else {
        data_V_data_5_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_5_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_5_V_read = ap_const_logic_1;
    } else {
        data_V_data_5_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_6_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_6_V_blk_n = data_V_data_6_V_empty_n.read();
    } else {
        data_V_data_6_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_6_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_6_V_read = ap_const_logic_1;
    } else {
        data_V_data_6_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_7_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_7_V_blk_n = data_V_data_7_V_empty_n.read();
    } else {
        data_V_data_7_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_7_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_7_V_read = ap_const_logic_1;
    } else {
        data_V_data_7_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_8_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_8_V_blk_n = data_V_data_8_V_empty_n.read();
    } else {
        data_V_data_8_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_8_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_8_V_read = ap_const_logic_1;
    } else {
        data_V_data_8_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_9_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        data_V_data_9_V_blk_n = data_V_data_9_V_empty_n.read();
    } else {
        data_V_data_9_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_data_V_data_9_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        data_V_data_9_V_read = ap_const_logic_1;
    } else {
        data_V_data_9_V_read = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_io_acc_block_signal_op25() {
    io_acc_block_signal_op25 = (data_V_data_0_V_empty_n.read() & data_V_data_1_V_empty_n.read() & data_V_data_2_V_empty_n.read() & data_V_data_3_V_empty_n.read() & data_V_data_4_V_empty_n.read() & data_V_data_5_V_empty_n.read() & data_V_data_6_V_empty_n.read() & data_V_data_7_V_empty_n.read() & data_V_data_8_V_empty_n.read() & data_V_data_9_V_empty_n.read());
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_io_acc_block_signal_op46() {
    io_acc_block_signal_op46 = (res_V_data_0_V_full_n.read() & res_V_data_1_V_full_n.read() & res_V_data_2_V_full_n.read() & res_V_data_3_V_full_n.read() & res_V_data_4_V_full_n.read() & res_V_data_5_V_full_n.read() & res_V_data_6_V_full_n.read() & res_V_data_7_V_full_n.read() & res_V_data_8_V_full_n.read() & res_V_data_9_V_full_n.read());
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n.read();
    } else {
        res_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_0_V_din() {
    res_V_data_0_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_0_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_0_V_write = ap_const_logic_1;
    } else {
        res_V_data_0_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n.read();
    } else {
        res_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_1_V_din() {
    res_V_data_1_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_1_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_1_V_write = ap_const_logic_1;
    } else {
        res_V_data_1_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n.read();
    } else {
        res_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_2_V_din() {
    res_V_data_2_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_2_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_2_V_write = ap_const_logic_1;
    } else {
        res_V_data_2_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_3_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n.read();
    } else {
        res_V_data_3_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_3_V_din() {
    res_V_data_3_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_3_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_3_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_3_V_write = ap_const_logic_1;
    } else {
        res_V_data_3_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_4_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n.read();
    } else {
        res_V_data_4_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_4_V_din() {
    res_V_data_4_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_4_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_4_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_4_V_write = ap_const_logic_1;
    } else {
        res_V_data_4_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_5_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n.read();
    } else {
        res_V_data_5_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_5_V_din() {
    res_V_data_5_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_5_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_5_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_5_V_write = ap_const_logic_1;
    } else {
        res_V_data_5_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_6_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n.read();
    } else {
        res_V_data_6_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_6_V_din() {
    res_V_data_6_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_6_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_6_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_6_V_write = ap_const_logic_1;
    } else {
        res_V_data_6_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_7_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n.read();
    } else {
        res_V_data_7_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_7_V_din() {
    res_V_data_7_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_7_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_7_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_7_V_write = ap_const_logic_1;
    } else {
        res_V_data_7_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_8_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_8_V_blk_n = res_V_data_8_V_full_n.read();
    } else {
        res_V_data_8_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_8_V_din() {
    res_V_data_8_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_8_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_8_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_8_V_write = ap_const_logic_1;
    } else {
        res_V_data_8_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_9_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        res_V_data_9_V_blk_n = res_V_data_9_V_full_n.read();
    } else {
        res_V_data_9_V_blk_n = ap_const_logic_1;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_9_V_din() {
    res_V_data_9_V_din = (!ap_const_lv14_2.is_01())? sc_lv<14>(): data_V_data_9_V_dout.read() << (unsigned short)ap_const_lv14_2.to_uint();
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_res_V_data_9_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op25.read()) || esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op46.read())))) {
        res_V_data_9_V_write = ap_const_logic_1;
    } else {
        res_V_data_9_V_write = ap_const_logic_0;
    }
}

void linear_array_array_ap_fixed_14_6_5_3_0_10u_linear_config13_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

