// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "myproject_axi.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<32> myproject_axi::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> myproject_axi::ap_const_lv1_0 = "0";
const sc_logic myproject_axi::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic myproject_axi::ap_const_logic_0 = sc_dt::Log_0;
const bool myproject_axi::ap_const_boolean_1 = true;

myproject_axi::myproject_axi(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Loop_1_proc225_U0 = new Loop_1_proc225("Loop_1_proc225_U0");
    Loop_1_proc225_U0->ap_clk(ap_clk);
    Loop_1_proc225_U0->ap_rst(ap_rst_n_inv);
    Loop_1_proc225_U0->ap_start(Loop_1_proc225_U0_ap_start);
    Loop_1_proc225_U0->start_full_n(start_for_myproject_U0_full_n);
    Loop_1_proc225_U0->ap_done(Loop_1_proc225_U0_ap_done);
    Loop_1_proc225_U0->ap_continue(Loop_1_proc225_U0_ap_continue);
    Loop_1_proc225_U0->ap_idle(Loop_1_proc225_U0_ap_idle);
    Loop_1_proc225_U0->ap_ready(Loop_1_proc225_U0_ap_ready);
    Loop_1_proc225_U0->start_out(Loop_1_proc225_U0_start_out);
    Loop_1_proc225_U0->start_write(Loop_1_proc225_U0_start_write);
    Loop_1_proc225_U0->in_local_V_data_0_V_din(Loop_1_proc225_U0_in_local_V_data_0_V_din);
    Loop_1_proc225_U0->in_local_V_data_0_V_full_n(in_local_V_data_0_V_full_n);
    Loop_1_proc225_U0->in_local_V_data_0_V_write(Loop_1_proc225_U0_in_local_V_data_0_V_write);
    Loop_1_proc225_U0->in_local_V_data_1_V_din(Loop_1_proc225_U0_in_local_V_data_1_V_din);
    Loop_1_proc225_U0->in_local_V_data_1_V_full_n(in_local_V_data_1_V_full_n);
    Loop_1_proc225_U0->in_local_V_data_1_V_write(Loop_1_proc225_U0_in_local_V_data_1_V_write);
    Loop_1_proc225_U0->in_local_V_data_2_V_din(Loop_1_proc225_U0_in_local_V_data_2_V_din);
    Loop_1_proc225_U0->in_local_V_data_2_V_full_n(in_local_V_data_2_V_full_n);
    Loop_1_proc225_U0->in_local_V_data_2_V_write(Loop_1_proc225_U0_in_local_V_data_2_V_write);
    Loop_1_proc225_U0->in_r_TLAST(in_r_TLAST);
    Loop_1_proc225_U0->in_r_TVALID(in_r_TVALID);
    Loop_1_proc225_U0->in_r_TREADY(Loop_1_proc225_U0_in_r_TREADY);
    Loop_1_proc225_U0->in_r_TDATA(in_r_TDATA);
    Loop_1_proc225_U0->ap_return(Loop_1_proc225_U0_ap_return);
    myproject_U0 = new myproject("myproject_U0");
    myproject_U0->ap_start(myproject_U0_ap_start);
    myproject_U0->start_full_n(start_for_Block_myproject_axi_exit52_proc_U0_full_n);
    myproject_U0->start_out(myproject_U0_start_out);
    myproject_U0->start_write(myproject_U0_start_write);
    myproject_U0->input_1_V_data_0_V_dout(in_local_V_data_0_V_dout);
    myproject_U0->input_1_V_data_0_V_empty_n(in_local_V_data_0_V_empty_n);
    myproject_U0->input_1_V_data_0_V_read(myproject_U0_input_1_V_data_0_V_read);
    myproject_U0->input_1_V_data_1_V_dout(in_local_V_data_1_V_dout);
    myproject_U0->input_1_V_data_1_V_empty_n(in_local_V_data_1_V_empty_n);
    myproject_U0->input_1_V_data_1_V_read(myproject_U0_input_1_V_data_1_V_read);
    myproject_U0->input_1_V_data_2_V_dout(in_local_V_data_2_V_dout);
    myproject_U0->input_1_V_data_2_V_empty_n(in_local_V_data_2_V_empty_n);
    myproject_U0->input_1_V_data_2_V_read(myproject_U0_input_1_V_data_2_V_read);
    myproject_U0->layer12_out_V_data_0_V_din(myproject_U0_layer12_out_V_data_0_V_din);
    myproject_U0->layer12_out_V_data_0_V_full_n(out_local_V_data_0_V_full_n);
    myproject_U0->layer12_out_V_data_0_V_write(myproject_U0_layer12_out_V_data_0_V_write);
    myproject_U0->layer12_out_V_data_1_V_din(myproject_U0_layer12_out_V_data_1_V_din);
    myproject_U0->layer12_out_V_data_1_V_full_n(out_local_V_data_1_V_full_n);
    myproject_U0->layer12_out_V_data_1_V_write(myproject_U0_layer12_out_V_data_1_V_write);
    myproject_U0->layer12_out_V_data_2_V_din(myproject_U0_layer12_out_V_data_2_V_din);
    myproject_U0->layer12_out_V_data_2_V_full_n(out_local_V_data_2_V_full_n);
    myproject_U0->layer12_out_V_data_2_V_write(myproject_U0_layer12_out_V_data_2_V_write);
    myproject_U0->layer12_out_V_data_3_V_din(myproject_U0_layer12_out_V_data_3_V_din);
    myproject_U0->layer12_out_V_data_3_V_full_n(out_local_V_data_3_V_full_n);
    myproject_U0->layer12_out_V_data_3_V_write(myproject_U0_layer12_out_V_data_3_V_write);
    myproject_U0->layer12_out_V_data_4_V_din(myproject_U0_layer12_out_V_data_4_V_din);
    myproject_U0->layer12_out_V_data_4_V_full_n(out_local_V_data_4_V_full_n);
    myproject_U0->layer12_out_V_data_4_V_write(myproject_U0_layer12_out_V_data_4_V_write);
    myproject_U0->layer12_out_V_data_5_V_din(myproject_U0_layer12_out_V_data_5_V_din);
    myproject_U0->layer12_out_V_data_5_V_full_n(out_local_V_data_5_V_full_n);
    myproject_U0->layer12_out_V_data_5_V_write(myproject_U0_layer12_out_V_data_5_V_write);
    myproject_U0->layer12_out_V_data_6_V_din(myproject_U0_layer12_out_V_data_6_V_din);
    myproject_U0->layer12_out_V_data_6_V_full_n(out_local_V_data_6_V_full_n);
    myproject_U0->layer12_out_V_data_6_V_write(myproject_U0_layer12_out_V_data_6_V_write);
    myproject_U0->layer12_out_V_data_7_V_din(myproject_U0_layer12_out_V_data_7_V_din);
    myproject_U0->layer12_out_V_data_7_V_full_n(out_local_V_data_7_V_full_n);
    myproject_U0->layer12_out_V_data_7_V_write(myproject_U0_layer12_out_V_data_7_V_write);
    myproject_U0->layer12_out_V_data_8_V_din(myproject_U0_layer12_out_V_data_8_V_din);
    myproject_U0->layer12_out_V_data_8_V_full_n(out_local_V_data_8_V_full_n);
    myproject_U0->layer12_out_V_data_8_V_write(myproject_U0_layer12_out_V_data_8_V_write);
    myproject_U0->layer12_out_V_data_9_V_din(myproject_U0_layer12_out_V_data_9_V_din);
    myproject_U0->layer12_out_V_data_9_V_full_n(out_local_V_data_9_V_full_n);
    myproject_U0->layer12_out_V_data_9_V_write(myproject_U0_layer12_out_V_data_9_V_write);
    myproject_U0->ap_clk(ap_clk);
    myproject_U0->ap_rst(ap_rst_n_inv);
    myproject_U0->ap_done(myproject_U0_ap_done);
    myproject_U0->ap_ready(myproject_U0_ap_ready);
    myproject_U0->ap_idle(myproject_U0_ap_idle);
    myproject_U0->ap_continue(myproject_U0_ap_continue);
    Block_myproject_axi_exit52_proc_U0 = new Block_myproject_axi_exit52_proc("Block_myproject_axi_exit52_proc_U0");
    Block_myproject_axi_exit52_proc_U0->ap_clk(ap_clk);
    Block_myproject_axi_exit52_proc_U0->ap_rst(ap_rst_n_inv);
    Block_myproject_axi_exit52_proc_U0->ap_start(Block_myproject_axi_exit52_proc_U0_ap_start);
    Block_myproject_axi_exit52_proc_U0->ap_done(Block_myproject_axi_exit52_proc_U0_ap_done);
    Block_myproject_axi_exit52_proc_U0->ap_continue(Block_myproject_axi_exit52_proc_U0_ap_continue);
    Block_myproject_axi_exit52_proc_U0->ap_idle(Block_myproject_axi_exit52_proc_U0_ap_idle);
    Block_myproject_axi_exit52_proc_U0->ap_ready(Block_myproject_axi_exit52_proc_U0_ap_ready);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_0_V_dout(out_local_V_data_0_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_0_V_empty_n(out_local_V_data_0_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_0_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_0_V_read);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_1_V_dout(out_local_V_data_1_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_1_V_empty_n(out_local_V_data_1_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_1_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_1_V_read);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_2_V_dout(out_local_V_data_2_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_2_V_empty_n(out_local_V_data_2_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_2_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_2_V_read);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_3_V_dout(out_local_V_data_3_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_3_V_empty_n(out_local_V_data_3_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_3_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_3_V_read);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_4_V_dout(out_local_V_data_4_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_4_V_empty_n(out_local_V_data_4_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_4_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_4_V_read);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_5_V_dout(out_local_V_data_5_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_5_V_empty_n(out_local_V_data_5_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_5_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_5_V_read);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_6_V_dout(out_local_V_data_6_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_6_V_empty_n(out_local_V_data_6_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_6_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_6_V_read);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_7_V_dout(out_local_V_data_7_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_7_V_empty_n(out_local_V_data_7_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_7_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_7_V_read);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_8_V_dout(out_local_V_data_8_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_8_V_empty_n(out_local_V_data_8_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_8_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_8_V_read);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_9_V_dout(out_local_V_data_9_V_dout);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_9_V_empty_n(out_local_V_data_9_V_empty_n);
    Block_myproject_axi_exit52_proc_U0->out_local_V_data_9_V_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_9_V_read);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_0(Block_myproject_axi_exit52_proc_U0_tmp_data_V_0);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_0_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_0_ap_vld);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_1(Block_myproject_axi_exit52_proc_U0_tmp_data_V_1);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_1_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_1_ap_vld);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_2(Block_myproject_axi_exit52_proc_U0_tmp_data_V_2);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_2_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_2_ap_vld);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_3(Block_myproject_axi_exit52_proc_U0_tmp_data_V_3);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_3_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_3_ap_vld);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_4(Block_myproject_axi_exit52_proc_U0_tmp_data_V_4);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_4_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_4_ap_vld);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_5(Block_myproject_axi_exit52_proc_U0_tmp_data_V_5);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_5_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_5_ap_vld);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_6(Block_myproject_axi_exit52_proc_U0_tmp_data_V_6);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_6_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_6_ap_vld);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_7(Block_myproject_axi_exit52_proc_U0_tmp_data_V_7);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_7_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_7_ap_vld);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_8(Block_myproject_axi_exit52_proc_U0_tmp_data_V_8);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_8_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_8_ap_vld);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_9(Block_myproject_axi_exit52_proc_U0_tmp_data_V_9);
    Block_myproject_axi_exit52_proc_U0->tmp_data_V_9_ap_vld(Block_myproject_axi_exit52_proc_U0_tmp_data_V_9_ap_vld);
    Loop_2_proc_U0 = new Loop_2_proc("Loop_2_proc_U0");
    Loop_2_proc_U0->ap_clk(ap_clk);
    Loop_2_proc_U0->ap_rst(ap_rst_n_inv);
    Loop_2_proc_U0->ap_start(Loop_2_proc_U0_ap_start);
    Loop_2_proc_U0->ap_done(Loop_2_proc_U0_ap_done);
    Loop_2_proc_U0->ap_continue(Loop_2_proc_U0_ap_continue);
    Loop_2_proc_U0->ap_idle(Loop_2_proc_U0_ap_idle);
    Loop_2_proc_U0->ap_ready(Loop_2_proc_U0_ap_ready);
    Loop_2_proc_U0->out_r_TDATA(Loop_2_proc_U0_out_r_TDATA);
    Loop_2_proc_U0->out_r_TVALID(Loop_2_proc_U0_out_r_TVALID);
    Loop_2_proc_U0->out_r_TREADY(out_r_TREADY);
    Loop_2_proc_U0->out_r_TLAST(Loop_2_proc_U0_out_r_TLAST);
    Loop_2_proc_U0->p_read(is_last_0_i_loc_channel_dout);
    Loop_2_proc_U0->tmp_data_V_0(tmp_data_V_0_dout);
    Loop_2_proc_U0->tmp_data_V_1(tmp_data_V_1_dout);
    Loop_2_proc_U0->tmp_data_V_2(tmp_data_V_2_dout);
    Loop_2_proc_U0->tmp_data_V_3(tmp_data_V_3_dout);
    Loop_2_proc_U0->tmp_data_V_4(tmp_data_V_4_dout);
    Loop_2_proc_U0->tmp_data_V_5(tmp_data_V_5_dout);
    Loop_2_proc_U0->tmp_data_V_6(tmp_data_V_6_dout);
    Loop_2_proc_U0->tmp_data_V_7(tmp_data_V_7_dout);
    Loop_2_proc_U0->tmp_data_V_8(tmp_data_V_8_dout);
    Loop_2_proc_U0->tmp_data_V_9(tmp_data_V_9_dout);
    in_local_V_data_0_V_U = new fifo_w8_d3072_A("in_local_V_data_0_V_U");
    in_local_V_data_0_V_U->clk(ap_clk);
    in_local_V_data_0_V_U->reset(ap_rst_n_inv);
    in_local_V_data_0_V_U->if_read_ce(ap_var_for_const0);
    in_local_V_data_0_V_U->if_write_ce(ap_var_for_const0);
    in_local_V_data_0_V_U->if_din(Loop_1_proc225_U0_in_local_V_data_0_V_din);
    in_local_V_data_0_V_U->if_full_n(in_local_V_data_0_V_full_n);
    in_local_V_data_0_V_U->if_write(Loop_1_proc225_U0_in_local_V_data_0_V_write);
    in_local_V_data_0_V_U->if_dout(in_local_V_data_0_V_dout);
    in_local_V_data_0_V_U->if_empty_n(in_local_V_data_0_V_empty_n);
    in_local_V_data_0_V_U->if_read(myproject_U0_input_1_V_data_0_V_read);
    in_local_V_data_1_V_U = new fifo_w8_d3072_A("in_local_V_data_1_V_U");
    in_local_V_data_1_V_U->clk(ap_clk);
    in_local_V_data_1_V_U->reset(ap_rst_n_inv);
    in_local_V_data_1_V_U->if_read_ce(ap_var_for_const0);
    in_local_V_data_1_V_U->if_write_ce(ap_var_for_const0);
    in_local_V_data_1_V_U->if_din(Loop_1_proc225_U0_in_local_V_data_1_V_din);
    in_local_V_data_1_V_U->if_full_n(in_local_V_data_1_V_full_n);
    in_local_V_data_1_V_U->if_write(Loop_1_proc225_U0_in_local_V_data_1_V_write);
    in_local_V_data_1_V_U->if_dout(in_local_V_data_1_V_dout);
    in_local_V_data_1_V_U->if_empty_n(in_local_V_data_1_V_empty_n);
    in_local_V_data_1_V_U->if_read(myproject_U0_input_1_V_data_1_V_read);
    in_local_V_data_2_V_U = new fifo_w8_d3072_A("in_local_V_data_2_V_U");
    in_local_V_data_2_V_U->clk(ap_clk);
    in_local_V_data_2_V_U->reset(ap_rst_n_inv);
    in_local_V_data_2_V_U->if_read_ce(ap_var_for_const0);
    in_local_V_data_2_V_U->if_write_ce(ap_var_for_const0);
    in_local_V_data_2_V_U->if_din(Loop_1_proc225_U0_in_local_V_data_2_V_din);
    in_local_V_data_2_V_U->if_full_n(in_local_V_data_2_V_full_n);
    in_local_V_data_2_V_U->if_write(Loop_1_proc225_U0_in_local_V_data_2_V_write);
    in_local_V_data_2_V_U->if_dout(in_local_V_data_2_V_dout);
    in_local_V_data_2_V_U->if_empty_n(in_local_V_data_2_V_empty_n);
    in_local_V_data_2_V_U->if_read(myproject_U0_input_1_V_data_2_V_read);
    is_last_0_i_loc_channel_U = new fifo_w1_d2_A("is_last_0_i_loc_channel_U");
    is_last_0_i_loc_channel_U->clk(ap_clk);
    is_last_0_i_loc_channel_U->reset(ap_rst_n_inv);
    is_last_0_i_loc_channel_U->if_read_ce(ap_var_for_const0);
    is_last_0_i_loc_channel_U->if_write_ce(ap_var_for_const0);
    is_last_0_i_loc_channel_U->if_din(Loop_1_proc225_U0_ap_return);
    is_last_0_i_loc_channel_U->if_full_n(is_last_0_i_loc_channel_full_n);
    is_last_0_i_loc_channel_U->if_write(Loop_1_proc225_U0_ap_done);
    is_last_0_i_loc_channel_U->if_dout(is_last_0_i_loc_channel_dout);
    is_last_0_i_loc_channel_U->if_empty_n(is_last_0_i_loc_channel_empty_n);
    is_last_0_i_loc_channel_U->if_read(Loop_2_proc_U0_ap_ready);
    out_local_V_data_0_V_U = new fifo_w8_d10_A("out_local_V_data_0_V_U");
    out_local_V_data_0_V_U->clk(ap_clk);
    out_local_V_data_0_V_U->reset(ap_rst_n_inv);
    out_local_V_data_0_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_0_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_0_V_U->if_din(myproject_U0_layer12_out_V_data_0_V_din);
    out_local_V_data_0_V_U->if_full_n(out_local_V_data_0_V_full_n);
    out_local_V_data_0_V_U->if_write(myproject_U0_layer12_out_V_data_0_V_write);
    out_local_V_data_0_V_U->if_dout(out_local_V_data_0_V_dout);
    out_local_V_data_0_V_U->if_empty_n(out_local_V_data_0_V_empty_n);
    out_local_V_data_0_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_0_V_read);
    out_local_V_data_1_V_U = new fifo_w8_d10_A("out_local_V_data_1_V_U");
    out_local_V_data_1_V_U->clk(ap_clk);
    out_local_V_data_1_V_U->reset(ap_rst_n_inv);
    out_local_V_data_1_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_1_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_1_V_U->if_din(myproject_U0_layer12_out_V_data_1_V_din);
    out_local_V_data_1_V_U->if_full_n(out_local_V_data_1_V_full_n);
    out_local_V_data_1_V_U->if_write(myproject_U0_layer12_out_V_data_1_V_write);
    out_local_V_data_1_V_U->if_dout(out_local_V_data_1_V_dout);
    out_local_V_data_1_V_U->if_empty_n(out_local_V_data_1_V_empty_n);
    out_local_V_data_1_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_1_V_read);
    out_local_V_data_2_V_U = new fifo_w8_d10_A("out_local_V_data_2_V_U");
    out_local_V_data_2_V_U->clk(ap_clk);
    out_local_V_data_2_V_U->reset(ap_rst_n_inv);
    out_local_V_data_2_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_2_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_2_V_U->if_din(myproject_U0_layer12_out_V_data_2_V_din);
    out_local_V_data_2_V_U->if_full_n(out_local_V_data_2_V_full_n);
    out_local_V_data_2_V_U->if_write(myproject_U0_layer12_out_V_data_2_V_write);
    out_local_V_data_2_V_U->if_dout(out_local_V_data_2_V_dout);
    out_local_V_data_2_V_U->if_empty_n(out_local_V_data_2_V_empty_n);
    out_local_V_data_2_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_2_V_read);
    out_local_V_data_3_V_U = new fifo_w8_d10_A("out_local_V_data_3_V_U");
    out_local_V_data_3_V_U->clk(ap_clk);
    out_local_V_data_3_V_U->reset(ap_rst_n_inv);
    out_local_V_data_3_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_3_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_3_V_U->if_din(myproject_U0_layer12_out_V_data_3_V_din);
    out_local_V_data_3_V_U->if_full_n(out_local_V_data_3_V_full_n);
    out_local_V_data_3_V_U->if_write(myproject_U0_layer12_out_V_data_3_V_write);
    out_local_V_data_3_V_U->if_dout(out_local_V_data_3_V_dout);
    out_local_V_data_3_V_U->if_empty_n(out_local_V_data_3_V_empty_n);
    out_local_V_data_3_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_3_V_read);
    out_local_V_data_4_V_U = new fifo_w8_d10_A("out_local_V_data_4_V_U");
    out_local_V_data_4_V_U->clk(ap_clk);
    out_local_V_data_4_V_U->reset(ap_rst_n_inv);
    out_local_V_data_4_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_4_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_4_V_U->if_din(myproject_U0_layer12_out_V_data_4_V_din);
    out_local_V_data_4_V_U->if_full_n(out_local_V_data_4_V_full_n);
    out_local_V_data_4_V_U->if_write(myproject_U0_layer12_out_V_data_4_V_write);
    out_local_V_data_4_V_U->if_dout(out_local_V_data_4_V_dout);
    out_local_V_data_4_V_U->if_empty_n(out_local_V_data_4_V_empty_n);
    out_local_V_data_4_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_4_V_read);
    out_local_V_data_5_V_U = new fifo_w8_d10_A("out_local_V_data_5_V_U");
    out_local_V_data_5_V_U->clk(ap_clk);
    out_local_V_data_5_V_U->reset(ap_rst_n_inv);
    out_local_V_data_5_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_5_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_5_V_U->if_din(myproject_U0_layer12_out_V_data_5_V_din);
    out_local_V_data_5_V_U->if_full_n(out_local_V_data_5_V_full_n);
    out_local_V_data_5_V_U->if_write(myproject_U0_layer12_out_V_data_5_V_write);
    out_local_V_data_5_V_U->if_dout(out_local_V_data_5_V_dout);
    out_local_V_data_5_V_U->if_empty_n(out_local_V_data_5_V_empty_n);
    out_local_V_data_5_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_5_V_read);
    out_local_V_data_6_V_U = new fifo_w8_d10_A("out_local_V_data_6_V_U");
    out_local_V_data_6_V_U->clk(ap_clk);
    out_local_V_data_6_V_U->reset(ap_rst_n_inv);
    out_local_V_data_6_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_6_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_6_V_U->if_din(myproject_U0_layer12_out_V_data_6_V_din);
    out_local_V_data_6_V_U->if_full_n(out_local_V_data_6_V_full_n);
    out_local_V_data_6_V_U->if_write(myproject_U0_layer12_out_V_data_6_V_write);
    out_local_V_data_6_V_U->if_dout(out_local_V_data_6_V_dout);
    out_local_V_data_6_V_U->if_empty_n(out_local_V_data_6_V_empty_n);
    out_local_V_data_6_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_6_V_read);
    out_local_V_data_7_V_U = new fifo_w8_d10_A("out_local_V_data_7_V_U");
    out_local_V_data_7_V_U->clk(ap_clk);
    out_local_V_data_7_V_U->reset(ap_rst_n_inv);
    out_local_V_data_7_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_7_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_7_V_U->if_din(myproject_U0_layer12_out_V_data_7_V_din);
    out_local_V_data_7_V_U->if_full_n(out_local_V_data_7_V_full_n);
    out_local_V_data_7_V_U->if_write(myproject_U0_layer12_out_V_data_7_V_write);
    out_local_V_data_7_V_U->if_dout(out_local_V_data_7_V_dout);
    out_local_V_data_7_V_U->if_empty_n(out_local_V_data_7_V_empty_n);
    out_local_V_data_7_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_7_V_read);
    out_local_V_data_8_V_U = new fifo_w8_d10_A("out_local_V_data_8_V_U");
    out_local_V_data_8_V_U->clk(ap_clk);
    out_local_V_data_8_V_U->reset(ap_rst_n_inv);
    out_local_V_data_8_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_8_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_8_V_U->if_din(myproject_U0_layer12_out_V_data_8_V_din);
    out_local_V_data_8_V_U->if_full_n(out_local_V_data_8_V_full_n);
    out_local_V_data_8_V_U->if_write(myproject_U0_layer12_out_V_data_8_V_write);
    out_local_V_data_8_V_U->if_dout(out_local_V_data_8_V_dout);
    out_local_V_data_8_V_U->if_empty_n(out_local_V_data_8_V_empty_n);
    out_local_V_data_8_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_8_V_read);
    out_local_V_data_9_V_U = new fifo_w8_d10_A("out_local_V_data_9_V_U");
    out_local_V_data_9_V_U->clk(ap_clk);
    out_local_V_data_9_V_U->reset(ap_rst_n_inv);
    out_local_V_data_9_V_U->if_read_ce(ap_var_for_const0);
    out_local_V_data_9_V_U->if_write_ce(ap_var_for_const0);
    out_local_V_data_9_V_U->if_din(myproject_U0_layer12_out_V_data_9_V_din);
    out_local_V_data_9_V_U->if_full_n(out_local_V_data_9_V_full_n);
    out_local_V_data_9_V_U->if_write(myproject_U0_layer12_out_V_data_9_V_write);
    out_local_V_data_9_V_U->if_dout(out_local_V_data_9_V_dout);
    out_local_V_data_9_V_U->if_empty_n(out_local_V_data_9_V_empty_n);
    out_local_V_data_9_V_U->if_read(Block_myproject_axi_exit52_proc_U0_out_local_V_data_9_V_read);
    tmp_data_V_0_U = new fifo_w8_d2_A("tmp_data_V_0_U");
    tmp_data_V_0_U->clk(ap_clk);
    tmp_data_V_0_U->reset(ap_rst_n_inv);
    tmp_data_V_0_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_0_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_0_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_0);
    tmp_data_V_0_U->if_full_n(tmp_data_V_0_full_n);
    tmp_data_V_0_U->if_write(ap_channel_done_tmp_data_V_0);
    tmp_data_V_0_U->if_dout(tmp_data_V_0_dout);
    tmp_data_V_0_U->if_empty_n(tmp_data_V_0_empty_n);
    tmp_data_V_0_U->if_read(Loop_2_proc_U0_ap_ready);
    tmp_data_V_1_U = new fifo_w8_d2_A("tmp_data_V_1_U");
    tmp_data_V_1_U->clk(ap_clk);
    tmp_data_V_1_U->reset(ap_rst_n_inv);
    tmp_data_V_1_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_1_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_1_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_1);
    tmp_data_V_1_U->if_full_n(tmp_data_V_1_full_n);
    tmp_data_V_1_U->if_write(ap_channel_done_tmp_data_V_1);
    tmp_data_V_1_U->if_dout(tmp_data_V_1_dout);
    tmp_data_V_1_U->if_empty_n(tmp_data_V_1_empty_n);
    tmp_data_V_1_U->if_read(Loop_2_proc_U0_ap_ready);
    tmp_data_V_2_U = new fifo_w8_d2_A("tmp_data_V_2_U");
    tmp_data_V_2_U->clk(ap_clk);
    tmp_data_V_2_U->reset(ap_rst_n_inv);
    tmp_data_V_2_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_2_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_2_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_2);
    tmp_data_V_2_U->if_full_n(tmp_data_V_2_full_n);
    tmp_data_V_2_U->if_write(ap_channel_done_tmp_data_V_2);
    tmp_data_V_2_U->if_dout(tmp_data_V_2_dout);
    tmp_data_V_2_U->if_empty_n(tmp_data_V_2_empty_n);
    tmp_data_V_2_U->if_read(Loop_2_proc_U0_ap_ready);
    tmp_data_V_3_U = new fifo_w8_d2_A("tmp_data_V_3_U");
    tmp_data_V_3_U->clk(ap_clk);
    tmp_data_V_3_U->reset(ap_rst_n_inv);
    tmp_data_V_3_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_3_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_3_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_3);
    tmp_data_V_3_U->if_full_n(tmp_data_V_3_full_n);
    tmp_data_V_3_U->if_write(ap_channel_done_tmp_data_V_3);
    tmp_data_V_3_U->if_dout(tmp_data_V_3_dout);
    tmp_data_V_3_U->if_empty_n(tmp_data_V_3_empty_n);
    tmp_data_V_3_U->if_read(Loop_2_proc_U0_ap_ready);
    tmp_data_V_4_U = new fifo_w8_d2_A("tmp_data_V_4_U");
    tmp_data_V_4_U->clk(ap_clk);
    tmp_data_V_4_U->reset(ap_rst_n_inv);
    tmp_data_V_4_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_4_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_4_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_4);
    tmp_data_V_4_U->if_full_n(tmp_data_V_4_full_n);
    tmp_data_V_4_U->if_write(ap_channel_done_tmp_data_V_4);
    tmp_data_V_4_U->if_dout(tmp_data_V_4_dout);
    tmp_data_V_4_U->if_empty_n(tmp_data_V_4_empty_n);
    tmp_data_V_4_U->if_read(Loop_2_proc_U0_ap_ready);
    tmp_data_V_5_U = new fifo_w8_d2_A("tmp_data_V_5_U");
    tmp_data_V_5_U->clk(ap_clk);
    tmp_data_V_5_U->reset(ap_rst_n_inv);
    tmp_data_V_5_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_5_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_5_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_5);
    tmp_data_V_5_U->if_full_n(tmp_data_V_5_full_n);
    tmp_data_V_5_U->if_write(ap_channel_done_tmp_data_V_5);
    tmp_data_V_5_U->if_dout(tmp_data_V_5_dout);
    tmp_data_V_5_U->if_empty_n(tmp_data_V_5_empty_n);
    tmp_data_V_5_U->if_read(Loop_2_proc_U0_ap_ready);
    tmp_data_V_6_U = new fifo_w8_d2_A("tmp_data_V_6_U");
    tmp_data_V_6_U->clk(ap_clk);
    tmp_data_V_6_U->reset(ap_rst_n_inv);
    tmp_data_V_6_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_6_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_6_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_6);
    tmp_data_V_6_U->if_full_n(tmp_data_V_6_full_n);
    tmp_data_V_6_U->if_write(ap_channel_done_tmp_data_V_6);
    tmp_data_V_6_U->if_dout(tmp_data_V_6_dout);
    tmp_data_V_6_U->if_empty_n(tmp_data_V_6_empty_n);
    tmp_data_V_6_U->if_read(Loop_2_proc_U0_ap_ready);
    tmp_data_V_7_U = new fifo_w8_d2_A("tmp_data_V_7_U");
    tmp_data_V_7_U->clk(ap_clk);
    tmp_data_V_7_U->reset(ap_rst_n_inv);
    tmp_data_V_7_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_7_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_7_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_7);
    tmp_data_V_7_U->if_full_n(tmp_data_V_7_full_n);
    tmp_data_V_7_U->if_write(ap_channel_done_tmp_data_V_7);
    tmp_data_V_7_U->if_dout(tmp_data_V_7_dout);
    tmp_data_V_7_U->if_empty_n(tmp_data_V_7_empty_n);
    tmp_data_V_7_U->if_read(Loop_2_proc_U0_ap_ready);
    tmp_data_V_8_U = new fifo_w8_d2_A("tmp_data_V_8_U");
    tmp_data_V_8_U->clk(ap_clk);
    tmp_data_V_8_U->reset(ap_rst_n_inv);
    tmp_data_V_8_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_8_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_8_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_8);
    tmp_data_V_8_U->if_full_n(tmp_data_V_8_full_n);
    tmp_data_V_8_U->if_write(ap_channel_done_tmp_data_V_8);
    tmp_data_V_8_U->if_dout(tmp_data_V_8_dout);
    tmp_data_V_8_U->if_empty_n(tmp_data_V_8_empty_n);
    tmp_data_V_8_U->if_read(Loop_2_proc_U0_ap_ready);
    tmp_data_V_9_U = new fifo_w8_d2_A("tmp_data_V_9_U");
    tmp_data_V_9_U->clk(ap_clk);
    tmp_data_V_9_U->reset(ap_rst_n_inv);
    tmp_data_V_9_U->if_read_ce(ap_var_for_const0);
    tmp_data_V_9_U->if_write_ce(ap_var_for_const0);
    tmp_data_V_9_U->if_din(Block_myproject_axi_exit52_proc_U0_tmp_data_V_9);
    tmp_data_V_9_U->if_full_n(tmp_data_V_9_full_n);
    tmp_data_V_9_U->if_write(ap_channel_done_tmp_data_V_9);
    tmp_data_V_9_U->if_dout(tmp_data_V_9_dout);
    tmp_data_V_9_U->if_empty_n(tmp_data_V_9_empty_n);
    tmp_data_V_9_U->if_read(Loop_2_proc_U0_ap_ready);
    start_for_myproject_U0_U = new start_for_myproject_U0("start_for_myproject_U0_U");
    start_for_myproject_U0_U->clk(ap_clk);
    start_for_myproject_U0_U->reset(ap_rst_n_inv);
    start_for_myproject_U0_U->if_read_ce(ap_var_for_const0);
    start_for_myproject_U0_U->if_write_ce(ap_var_for_const0);
    start_for_myproject_U0_U->if_din(start_for_myproject_U0_din);
    start_for_myproject_U0_U->if_full_n(start_for_myproject_U0_full_n);
    start_for_myproject_U0_U->if_write(Loop_1_proc225_U0_start_write);
    start_for_myproject_U0_U->if_dout(start_for_myproject_U0_dout);
    start_for_myproject_U0_U->if_empty_n(start_for_myproject_U0_empty_n);
    start_for_myproject_U0_U->if_read(myproject_U0_ap_ready);
    start_for_Block_myproject_axi_exit52_proc_U0_U = new start_for_Block_myproject_axi_exit52_proc_U0("start_for_Block_myproject_axi_exit52_proc_U0_U");
    start_for_Block_myproject_axi_exit52_proc_U0_U->clk(ap_clk);
    start_for_Block_myproject_axi_exit52_proc_U0_U->reset(ap_rst_n_inv);
    start_for_Block_myproject_axi_exit52_proc_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Block_myproject_axi_exit52_proc_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Block_myproject_axi_exit52_proc_U0_U->if_din(start_for_Block_myproject_axi_exit52_proc_U0_din);
    start_for_Block_myproject_axi_exit52_proc_U0_U->if_full_n(start_for_Block_myproject_axi_exit52_proc_U0_full_n);
    start_for_Block_myproject_axi_exit52_proc_U0_U->if_write(myproject_U0_start_write);
    start_for_Block_myproject_axi_exit52_proc_U0_U->if_dout(start_for_Block_myproject_axi_exit52_proc_U0_dout);
    start_for_Block_myproject_axi_exit52_proc_U0_U->if_empty_n(start_for_Block_myproject_axi_exit52_proc_U0_empty_n);
    start_for_Block_myproject_axi_exit52_proc_U0_U->if_read(Block_myproject_axi_exit52_proc_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Block_myproject_axi_exit52_proc_U0_ap_continue);
    sensitive << ( ap_sync_channel_write_tmp_data_V_9 );
    sensitive << ( ap_sync_channel_write_tmp_data_V_8 );
    sensitive << ( ap_sync_channel_write_tmp_data_V_7 );
    sensitive << ( ap_sync_channel_write_tmp_data_V_6 );
    sensitive << ( ap_sync_channel_write_tmp_data_V_5 );
    sensitive << ( ap_sync_channel_write_tmp_data_V_4 );
    sensitive << ( ap_sync_channel_write_tmp_data_V_3 );
    sensitive << ( ap_sync_channel_write_tmp_data_V_2 );
    sensitive << ( ap_sync_channel_write_tmp_data_V_1 );
    sensitive << ( ap_sync_channel_write_tmp_data_V_0 );

    SC_METHOD(thread_Block_myproject_axi_exit52_proc_U0_ap_start);
    sensitive << ( start_for_Block_myproject_axi_exit52_proc_U0_empty_n );

    SC_METHOD(thread_Block_myproject_axi_exit52_proc_U0_start_full_n);

    SC_METHOD(thread_Block_myproject_axi_exit52_proc_U0_start_write);

    SC_METHOD(thread_Loop_1_proc225_U0_ap_continue);
    sensitive << ( is_last_0_i_loc_channel_full_n );

    SC_METHOD(thread_Loop_1_proc225_U0_ap_start);

    SC_METHOD(thread_Loop_2_proc_U0_ap_continue);

    SC_METHOD(thread_Loop_2_proc_U0_ap_start);
    sensitive << ( is_last_0_i_loc_channel_empty_n );
    sensitive << ( tmp_data_V_0_empty_n );
    sensitive << ( tmp_data_V_1_empty_n );
    sensitive << ( tmp_data_V_2_empty_n );
    sensitive << ( tmp_data_V_3_empty_n );
    sensitive << ( tmp_data_V_4_empty_n );
    sensitive << ( tmp_data_V_5_empty_n );
    sensitive << ( tmp_data_V_6_empty_n );
    sensitive << ( tmp_data_V_7_empty_n );
    sensitive << ( tmp_data_V_8_empty_n );
    sensitive << ( tmp_data_V_9_empty_n );

    SC_METHOD(thread_Loop_2_proc_U0_start_full_n);

    SC_METHOD(thread_Loop_2_proc_U0_start_write);

    SC_METHOD(thread_ap_channel_done_is_last_0_i_loc_channel);
    sensitive << ( Loop_1_proc225_U0_ap_done );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_0);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_0 );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_1);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_1 );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_2);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_2 );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_3);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_3 );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_4);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_4 );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_5);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_5 );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_6);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_6 );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_7);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_7 );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_8);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_8 );

    SC_METHOD(thread_ap_channel_done_tmp_data_V_9);
    sensitive << ( Block_myproject_axi_exit52_proc_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_9 );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_0);
    sensitive << ( ap_channel_done_tmp_data_V_0 );
    sensitive << ( tmp_data_V_0_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_0 );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_1);
    sensitive << ( ap_channel_done_tmp_data_V_1 );
    sensitive << ( tmp_data_V_1_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_1 );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_2);
    sensitive << ( ap_channel_done_tmp_data_V_2 );
    sensitive << ( tmp_data_V_2_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_2 );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_3);
    sensitive << ( ap_channel_done_tmp_data_V_3 );
    sensitive << ( tmp_data_V_3_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_3 );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_4);
    sensitive << ( ap_channel_done_tmp_data_V_4 );
    sensitive << ( tmp_data_V_4_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_4 );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_5);
    sensitive << ( ap_channel_done_tmp_data_V_5 );
    sensitive << ( tmp_data_V_5_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_5 );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_6);
    sensitive << ( ap_channel_done_tmp_data_V_6 );
    sensitive << ( tmp_data_V_6_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_6 );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_7);
    sensitive << ( ap_channel_done_tmp_data_V_7 );
    sensitive << ( tmp_data_V_7_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_7 );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_8);
    sensitive << ( ap_channel_done_tmp_data_V_8 );
    sensitive << ( tmp_data_V_8_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_8 );

    SC_METHOD(thread_ap_sync_channel_write_tmp_data_V_9);
    sensitive << ( ap_channel_done_tmp_data_V_9 );
    sensitive << ( tmp_data_V_9_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_data_V_9 );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_in_r_TREADY);
    sensitive << ( Loop_1_proc225_U0_in_r_TREADY );

    SC_METHOD(thread_myproject_U0_ap_continue);

    SC_METHOD(thread_myproject_U0_ap_start);
    sensitive << ( start_for_myproject_U0_empty_n );

    SC_METHOD(thread_out_r_TDATA);
    sensitive << ( Loop_2_proc_U0_out_r_TDATA );

    SC_METHOD(thread_out_r_TLAST);
    sensitive << ( Loop_2_proc_U0_out_r_TLAST );

    SC_METHOD(thread_out_r_TVALID);
    sensitive << ( Loop_2_proc_U0_out_r_TVALID );

    SC_METHOD(thread_start_for_Block_myproject_axi_exit52_proc_U0_din);

    SC_METHOD(thread_start_for_myproject_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_channel_write_tmp_data_V_9 = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_data_V_8 = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_data_V_7 = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_data_V_6 = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_data_V_5 = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_data_V_4 = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_data_V_3 = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_data_V_2 = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_data_V_1 = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_data_V_0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "myproject_axi_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, in_r_TDATA, "(port)in_r_TDATA");
    sc_trace(mVcdFile, in_r_TLAST, "(port)in_r_TLAST");
    sc_trace(mVcdFile, out_r_TDATA, "(port)out_r_TDATA");
    sc_trace(mVcdFile, out_r_TLAST, "(port)out_r_TLAST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, in_r_TVALID, "(port)in_r_TVALID");
    sc_trace(mVcdFile, in_r_TREADY, "(port)in_r_TREADY");
    sc_trace(mVcdFile, out_r_TVALID, "(port)out_r_TVALID");
    sc_trace(mVcdFile, out_r_TREADY, "(port)out_r_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, Loop_1_proc225_U0_ap_start, "Loop_1_proc225_U0_ap_start");
    sc_trace(mVcdFile, Loop_1_proc225_U0_ap_done, "Loop_1_proc225_U0_ap_done");
    sc_trace(mVcdFile, Loop_1_proc225_U0_ap_continue, "Loop_1_proc225_U0_ap_continue");
    sc_trace(mVcdFile, Loop_1_proc225_U0_ap_idle, "Loop_1_proc225_U0_ap_idle");
    sc_trace(mVcdFile, Loop_1_proc225_U0_ap_ready, "Loop_1_proc225_U0_ap_ready");
    sc_trace(mVcdFile, Loop_1_proc225_U0_start_out, "Loop_1_proc225_U0_start_out");
    sc_trace(mVcdFile, Loop_1_proc225_U0_start_write, "Loop_1_proc225_U0_start_write");
    sc_trace(mVcdFile, Loop_1_proc225_U0_in_local_V_data_0_V_din, "Loop_1_proc225_U0_in_local_V_data_0_V_din");
    sc_trace(mVcdFile, Loop_1_proc225_U0_in_local_V_data_0_V_write, "Loop_1_proc225_U0_in_local_V_data_0_V_write");
    sc_trace(mVcdFile, Loop_1_proc225_U0_in_local_V_data_1_V_din, "Loop_1_proc225_U0_in_local_V_data_1_V_din");
    sc_trace(mVcdFile, Loop_1_proc225_U0_in_local_V_data_1_V_write, "Loop_1_proc225_U0_in_local_V_data_1_V_write");
    sc_trace(mVcdFile, Loop_1_proc225_U0_in_local_V_data_2_V_din, "Loop_1_proc225_U0_in_local_V_data_2_V_din");
    sc_trace(mVcdFile, Loop_1_proc225_U0_in_local_V_data_2_V_write, "Loop_1_proc225_U0_in_local_V_data_2_V_write");
    sc_trace(mVcdFile, Loop_1_proc225_U0_in_r_TREADY, "Loop_1_proc225_U0_in_r_TREADY");
    sc_trace(mVcdFile, Loop_1_proc225_U0_ap_return, "Loop_1_proc225_U0_ap_return");
    sc_trace(mVcdFile, ap_channel_done_is_last_0_i_loc_channel, "ap_channel_done_is_last_0_i_loc_channel");
    sc_trace(mVcdFile, is_last_0_i_loc_channel_full_n, "is_last_0_i_loc_channel_full_n");
    sc_trace(mVcdFile, myproject_U0_ap_start, "myproject_U0_ap_start");
    sc_trace(mVcdFile, myproject_U0_start_out, "myproject_U0_start_out");
    sc_trace(mVcdFile, myproject_U0_start_write, "myproject_U0_start_write");
    sc_trace(mVcdFile, myproject_U0_input_1_V_data_0_V_read, "myproject_U0_input_1_V_data_0_V_read");
    sc_trace(mVcdFile, myproject_U0_input_1_V_data_1_V_read, "myproject_U0_input_1_V_data_1_V_read");
    sc_trace(mVcdFile, myproject_U0_input_1_V_data_2_V_read, "myproject_U0_input_1_V_data_2_V_read");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_0_V_din, "myproject_U0_layer12_out_V_data_0_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_0_V_write, "myproject_U0_layer12_out_V_data_0_V_write");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_1_V_din, "myproject_U0_layer12_out_V_data_1_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_1_V_write, "myproject_U0_layer12_out_V_data_1_V_write");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_2_V_din, "myproject_U0_layer12_out_V_data_2_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_2_V_write, "myproject_U0_layer12_out_V_data_2_V_write");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_3_V_din, "myproject_U0_layer12_out_V_data_3_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_3_V_write, "myproject_U0_layer12_out_V_data_3_V_write");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_4_V_din, "myproject_U0_layer12_out_V_data_4_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_4_V_write, "myproject_U0_layer12_out_V_data_4_V_write");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_5_V_din, "myproject_U0_layer12_out_V_data_5_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_5_V_write, "myproject_U0_layer12_out_V_data_5_V_write");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_6_V_din, "myproject_U0_layer12_out_V_data_6_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_6_V_write, "myproject_U0_layer12_out_V_data_6_V_write");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_7_V_din, "myproject_U0_layer12_out_V_data_7_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_7_V_write, "myproject_U0_layer12_out_V_data_7_V_write");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_8_V_din, "myproject_U0_layer12_out_V_data_8_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_8_V_write, "myproject_U0_layer12_out_V_data_8_V_write");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_9_V_din, "myproject_U0_layer12_out_V_data_9_V_din");
    sc_trace(mVcdFile, myproject_U0_layer12_out_V_data_9_V_write, "myproject_U0_layer12_out_V_data_9_V_write");
    sc_trace(mVcdFile, myproject_U0_ap_done, "myproject_U0_ap_done");
    sc_trace(mVcdFile, myproject_U0_ap_ready, "myproject_U0_ap_ready");
    sc_trace(mVcdFile, myproject_U0_ap_idle, "myproject_U0_ap_idle");
    sc_trace(mVcdFile, myproject_U0_ap_continue, "myproject_U0_ap_continue");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_ap_start, "Block_myproject_axi_exit52_proc_U0_ap_start");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_ap_done, "Block_myproject_axi_exit52_proc_U0_ap_done");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_ap_continue, "Block_myproject_axi_exit52_proc_U0_ap_continue");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_ap_idle, "Block_myproject_axi_exit52_proc_U0_ap_idle");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_ap_ready, "Block_myproject_axi_exit52_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_0_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_0_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_1_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_1_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_2_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_2_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_3_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_3_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_4_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_4_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_5_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_5_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_6_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_6_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_7_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_7_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_8_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_8_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_out_local_V_data_9_V_read, "Block_myproject_axi_exit52_proc_U0_out_local_V_data_9_V_read");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_0, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_0");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_0_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_0_ap_vld");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_1, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_1");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_1_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_1_ap_vld");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_2, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_2");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_2_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_2_ap_vld");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_3, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_3");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_3_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_3_ap_vld");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_4, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_4");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_4_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_4_ap_vld");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_5, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_5");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_5_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_5_ap_vld");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_6, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_6");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_6_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_6_ap_vld");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_7, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_7");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_7_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_7_ap_vld");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_8, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_8");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_8_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_8_ap_vld");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_9, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_9");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_tmp_data_V_9_ap_vld, "Block_myproject_axi_exit52_proc_U0_tmp_data_V_9_ap_vld");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_9, "ap_channel_done_tmp_data_V_9");
    sc_trace(mVcdFile, tmp_data_V_9_full_n, "tmp_data_V_9_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_9, "ap_sync_reg_channel_write_tmp_data_V_9");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_9, "ap_sync_channel_write_tmp_data_V_9");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_8, "ap_channel_done_tmp_data_V_8");
    sc_trace(mVcdFile, tmp_data_V_8_full_n, "tmp_data_V_8_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_8, "ap_sync_reg_channel_write_tmp_data_V_8");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_8, "ap_sync_channel_write_tmp_data_V_8");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_7, "ap_channel_done_tmp_data_V_7");
    sc_trace(mVcdFile, tmp_data_V_7_full_n, "tmp_data_V_7_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_7, "ap_sync_reg_channel_write_tmp_data_V_7");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_7, "ap_sync_channel_write_tmp_data_V_7");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_6, "ap_channel_done_tmp_data_V_6");
    sc_trace(mVcdFile, tmp_data_V_6_full_n, "tmp_data_V_6_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_6, "ap_sync_reg_channel_write_tmp_data_V_6");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_6, "ap_sync_channel_write_tmp_data_V_6");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_5, "ap_channel_done_tmp_data_V_5");
    sc_trace(mVcdFile, tmp_data_V_5_full_n, "tmp_data_V_5_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_5, "ap_sync_reg_channel_write_tmp_data_V_5");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_5, "ap_sync_channel_write_tmp_data_V_5");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_4, "ap_channel_done_tmp_data_V_4");
    sc_trace(mVcdFile, tmp_data_V_4_full_n, "tmp_data_V_4_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_4, "ap_sync_reg_channel_write_tmp_data_V_4");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_4, "ap_sync_channel_write_tmp_data_V_4");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_3, "ap_channel_done_tmp_data_V_3");
    sc_trace(mVcdFile, tmp_data_V_3_full_n, "tmp_data_V_3_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_3, "ap_sync_reg_channel_write_tmp_data_V_3");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_3, "ap_sync_channel_write_tmp_data_V_3");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_2, "ap_channel_done_tmp_data_V_2");
    sc_trace(mVcdFile, tmp_data_V_2_full_n, "tmp_data_V_2_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_2, "ap_sync_reg_channel_write_tmp_data_V_2");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_2, "ap_sync_channel_write_tmp_data_V_2");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_1, "ap_channel_done_tmp_data_V_1");
    sc_trace(mVcdFile, tmp_data_V_1_full_n, "tmp_data_V_1_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_1, "ap_sync_reg_channel_write_tmp_data_V_1");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_1, "ap_sync_channel_write_tmp_data_V_1");
    sc_trace(mVcdFile, ap_channel_done_tmp_data_V_0, "ap_channel_done_tmp_data_V_0");
    sc_trace(mVcdFile, tmp_data_V_0_full_n, "tmp_data_V_0_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_data_V_0, "ap_sync_reg_channel_write_tmp_data_V_0");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_data_V_0, "ap_sync_channel_write_tmp_data_V_0");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_start, "Loop_2_proc_U0_ap_start");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_done, "Loop_2_proc_U0_ap_done");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_continue, "Loop_2_proc_U0_ap_continue");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_idle, "Loop_2_proc_U0_ap_idle");
    sc_trace(mVcdFile, Loop_2_proc_U0_ap_ready, "Loop_2_proc_U0_ap_ready");
    sc_trace(mVcdFile, Loop_2_proc_U0_out_r_TDATA, "Loop_2_proc_U0_out_r_TDATA");
    sc_trace(mVcdFile, Loop_2_proc_U0_out_r_TVALID, "Loop_2_proc_U0_out_r_TVALID");
    sc_trace(mVcdFile, Loop_2_proc_U0_out_r_TLAST, "Loop_2_proc_U0_out_r_TLAST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, in_local_V_data_0_V_full_n, "in_local_V_data_0_V_full_n");
    sc_trace(mVcdFile, in_local_V_data_0_V_dout, "in_local_V_data_0_V_dout");
    sc_trace(mVcdFile, in_local_V_data_0_V_empty_n, "in_local_V_data_0_V_empty_n");
    sc_trace(mVcdFile, in_local_V_data_1_V_full_n, "in_local_V_data_1_V_full_n");
    sc_trace(mVcdFile, in_local_V_data_1_V_dout, "in_local_V_data_1_V_dout");
    sc_trace(mVcdFile, in_local_V_data_1_V_empty_n, "in_local_V_data_1_V_empty_n");
    sc_trace(mVcdFile, in_local_V_data_2_V_full_n, "in_local_V_data_2_V_full_n");
    sc_trace(mVcdFile, in_local_V_data_2_V_dout, "in_local_V_data_2_V_dout");
    sc_trace(mVcdFile, in_local_V_data_2_V_empty_n, "in_local_V_data_2_V_empty_n");
    sc_trace(mVcdFile, is_last_0_i_loc_channel_dout, "is_last_0_i_loc_channel_dout");
    sc_trace(mVcdFile, is_last_0_i_loc_channel_empty_n, "is_last_0_i_loc_channel_empty_n");
    sc_trace(mVcdFile, out_local_V_data_0_V_full_n, "out_local_V_data_0_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_0_V_dout, "out_local_V_data_0_V_dout");
    sc_trace(mVcdFile, out_local_V_data_0_V_empty_n, "out_local_V_data_0_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_1_V_full_n, "out_local_V_data_1_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_1_V_dout, "out_local_V_data_1_V_dout");
    sc_trace(mVcdFile, out_local_V_data_1_V_empty_n, "out_local_V_data_1_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_2_V_full_n, "out_local_V_data_2_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_2_V_dout, "out_local_V_data_2_V_dout");
    sc_trace(mVcdFile, out_local_V_data_2_V_empty_n, "out_local_V_data_2_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_3_V_full_n, "out_local_V_data_3_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_3_V_dout, "out_local_V_data_3_V_dout");
    sc_trace(mVcdFile, out_local_V_data_3_V_empty_n, "out_local_V_data_3_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_4_V_full_n, "out_local_V_data_4_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_4_V_dout, "out_local_V_data_4_V_dout");
    sc_trace(mVcdFile, out_local_V_data_4_V_empty_n, "out_local_V_data_4_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_5_V_full_n, "out_local_V_data_5_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_5_V_dout, "out_local_V_data_5_V_dout");
    sc_trace(mVcdFile, out_local_V_data_5_V_empty_n, "out_local_V_data_5_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_6_V_full_n, "out_local_V_data_6_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_6_V_dout, "out_local_V_data_6_V_dout");
    sc_trace(mVcdFile, out_local_V_data_6_V_empty_n, "out_local_V_data_6_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_7_V_full_n, "out_local_V_data_7_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_7_V_dout, "out_local_V_data_7_V_dout");
    sc_trace(mVcdFile, out_local_V_data_7_V_empty_n, "out_local_V_data_7_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_8_V_full_n, "out_local_V_data_8_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_8_V_dout, "out_local_V_data_8_V_dout");
    sc_trace(mVcdFile, out_local_V_data_8_V_empty_n, "out_local_V_data_8_V_empty_n");
    sc_trace(mVcdFile, out_local_V_data_9_V_full_n, "out_local_V_data_9_V_full_n");
    sc_trace(mVcdFile, out_local_V_data_9_V_dout, "out_local_V_data_9_V_dout");
    sc_trace(mVcdFile, out_local_V_data_9_V_empty_n, "out_local_V_data_9_V_empty_n");
    sc_trace(mVcdFile, tmp_data_V_0_dout, "tmp_data_V_0_dout");
    sc_trace(mVcdFile, tmp_data_V_0_empty_n, "tmp_data_V_0_empty_n");
    sc_trace(mVcdFile, tmp_data_V_1_dout, "tmp_data_V_1_dout");
    sc_trace(mVcdFile, tmp_data_V_1_empty_n, "tmp_data_V_1_empty_n");
    sc_trace(mVcdFile, tmp_data_V_2_dout, "tmp_data_V_2_dout");
    sc_trace(mVcdFile, tmp_data_V_2_empty_n, "tmp_data_V_2_empty_n");
    sc_trace(mVcdFile, tmp_data_V_3_dout, "tmp_data_V_3_dout");
    sc_trace(mVcdFile, tmp_data_V_3_empty_n, "tmp_data_V_3_empty_n");
    sc_trace(mVcdFile, tmp_data_V_4_dout, "tmp_data_V_4_dout");
    sc_trace(mVcdFile, tmp_data_V_4_empty_n, "tmp_data_V_4_empty_n");
    sc_trace(mVcdFile, tmp_data_V_5_dout, "tmp_data_V_5_dout");
    sc_trace(mVcdFile, tmp_data_V_5_empty_n, "tmp_data_V_5_empty_n");
    sc_trace(mVcdFile, tmp_data_V_6_dout, "tmp_data_V_6_dout");
    sc_trace(mVcdFile, tmp_data_V_6_empty_n, "tmp_data_V_6_empty_n");
    sc_trace(mVcdFile, tmp_data_V_7_dout, "tmp_data_V_7_dout");
    sc_trace(mVcdFile, tmp_data_V_7_empty_n, "tmp_data_V_7_empty_n");
    sc_trace(mVcdFile, tmp_data_V_8_dout, "tmp_data_V_8_dout");
    sc_trace(mVcdFile, tmp_data_V_8_empty_n, "tmp_data_V_8_empty_n");
    sc_trace(mVcdFile, tmp_data_V_9_dout, "tmp_data_V_9_dout");
    sc_trace(mVcdFile, tmp_data_V_9_empty_n, "tmp_data_V_9_empty_n");
    sc_trace(mVcdFile, start_for_myproject_U0_din, "start_for_myproject_U0_din");
    sc_trace(mVcdFile, start_for_myproject_U0_full_n, "start_for_myproject_U0_full_n");
    sc_trace(mVcdFile, start_for_myproject_U0_dout, "start_for_myproject_U0_dout");
    sc_trace(mVcdFile, start_for_myproject_U0_empty_n, "start_for_myproject_U0_empty_n");
    sc_trace(mVcdFile, start_for_Block_myproject_axi_exit52_proc_U0_din, "start_for_Block_myproject_axi_exit52_proc_U0_din");
    sc_trace(mVcdFile, start_for_Block_myproject_axi_exit52_proc_U0_full_n, "start_for_Block_myproject_axi_exit52_proc_U0_full_n");
    sc_trace(mVcdFile, start_for_Block_myproject_axi_exit52_proc_U0_dout, "start_for_Block_myproject_axi_exit52_proc_U0_dout");
    sc_trace(mVcdFile, start_for_Block_myproject_axi_exit52_proc_U0_empty_n, "start_for_Block_myproject_axi_exit52_proc_U0_empty_n");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_start_full_n, "Block_myproject_axi_exit52_proc_U0_start_full_n");
    sc_trace(mVcdFile, Block_myproject_axi_exit52_proc_U0_start_write, "Block_myproject_axi_exit52_proc_U0_start_write");
    sc_trace(mVcdFile, Loop_2_proc_U0_start_full_n, "Loop_2_proc_U0_start_full_n");
    sc_trace(mVcdFile, Loop_2_proc_U0_start_write, "Loop_2_proc_U0_start_write");
#endif

    }
    mHdltvinHandle.open("myproject_axi.hdltvin.dat");
    mHdltvoutHandle.open("myproject_axi.hdltvout.dat");
}

myproject_axi::~myproject_axi() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Loop_1_proc225_U0;
    delete myproject_U0;
    delete Block_myproject_axi_exit52_proc_U0;
    delete Loop_2_proc_U0;
    delete in_local_V_data_0_V_U;
    delete in_local_V_data_1_V_U;
    delete in_local_V_data_2_V_U;
    delete is_last_0_i_loc_channel_U;
    delete out_local_V_data_0_V_U;
    delete out_local_V_data_1_V_U;
    delete out_local_V_data_2_V_U;
    delete out_local_V_data_3_V_U;
    delete out_local_V_data_4_V_U;
    delete out_local_V_data_5_V_U;
    delete out_local_V_data_6_V_U;
    delete out_local_V_data_7_V_U;
    delete out_local_V_data_8_V_U;
    delete out_local_V_data_9_V_U;
    delete tmp_data_V_0_U;
    delete tmp_data_V_1_U;
    delete tmp_data_V_2_U;
    delete tmp_data_V_3_U;
    delete tmp_data_V_4_U;
    delete tmp_data_V_5_U;
    delete tmp_data_V_6_U;
    delete tmp_data_V_7_U;
    delete tmp_data_V_8_U;
    delete tmp_data_V_9_U;
    delete start_for_myproject_U0_U;
    delete start_for_Block_myproject_axi_exit52_proc_U0_U;
}

void myproject_axi::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void myproject_axi::thread_ap_clk_no_reset_() {
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_0 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_0 = ap_sync_channel_write_tmp_data_V_0.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_1 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_1 = ap_sync_channel_write_tmp_data_V_1.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_2 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_2 = ap_sync_channel_write_tmp_data_V_2.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_3 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_3 = ap_sync_channel_write_tmp_data_V_3.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_4 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_4 = ap_sync_channel_write_tmp_data_V_4.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_5 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_5 = ap_sync_channel_write_tmp_data_V_5.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_6 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_6 = ap_sync_channel_write_tmp_data_V_6.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_7 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_7 = ap_sync_channel_write_tmp_data_V_7.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_8 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_8 = ap_sync_channel_write_tmp_data_V_8.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_data_V_9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_myproject_axi_exit52_proc_U0_ap_done.read() & 
             Block_myproject_axi_exit52_proc_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_data_V_9 = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_data_V_9 = ap_sync_channel_write_tmp_data_V_9.read();
        }
    }
}

void myproject_axi::thread_Block_myproject_axi_exit52_proc_U0_ap_continue() {
    Block_myproject_axi_exit52_proc_U0_ap_continue = (ap_sync_channel_write_tmp_data_V_9.read() & ap_sync_channel_write_tmp_data_V_8.read() & ap_sync_channel_write_tmp_data_V_7.read() & ap_sync_channel_write_tmp_data_V_6.read() & ap_sync_channel_write_tmp_data_V_5.read() & ap_sync_channel_write_tmp_data_V_4.read() & ap_sync_channel_write_tmp_data_V_3.read() & ap_sync_channel_write_tmp_data_V_2.read() & ap_sync_channel_write_tmp_data_V_1.read() & ap_sync_channel_write_tmp_data_V_0.read());
}

void myproject_axi::thread_Block_myproject_axi_exit52_proc_U0_ap_start() {
    Block_myproject_axi_exit52_proc_U0_ap_start = start_for_Block_myproject_axi_exit52_proc_U0_empty_n.read();
}

void myproject_axi::thread_Block_myproject_axi_exit52_proc_U0_start_full_n() {
    Block_myproject_axi_exit52_proc_U0_start_full_n = ap_const_logic_1;
}

void myproject_axi::thread_Block_myproject_axi_exit52_proc_U0_start_write() {
    Block_myproject_axi_exit52_proc_U0_start_write = ap_const_logic_0;
}

void myproject_axi::thread_Loop_1_proc225_U0_ap_continue() {
    Loop_1_proc225_U0_ap_continue = is_last_0_i_loc_channel_full_n.read();
}

void myproject_axi::thread_Loop_1_proc225_U0_ap_start() {
    Loop_1_proc225_U0_ap_start = ap_const_logic_1;
}

void myproject_axi::thread_Loop_2_proc_U0_ap_continue() {
    Loop_2_proc_U0_ap_continue = ap_const_logic_1;
}

void myproject_axi::thread_Loop_2_proc_U0_ap_start() {
    Loop_2_proc_U0_ap_start = (is_last_0_i_loc_channel_empty_n.read() & tmp_data_V_0_empty_n.read() & tmp_data_V_1_empty_n.read() & tmp_data_V_2_empty_n.read() & tmp_data_V_3_empty_n.read() & tmp_data_V_4_empty_n.read() & tmp_data_V_5_empty_n.read() & tmp_data_V_6_empty_n.read() & tmp_data_V_7_empty_n.read() & tmp_data_V_8_empty_n.read() & tmp_data_V_9_empty_n.read());
}

void myproject_axi::thread_Loop_2_proc_U0_start_full_n() {
    Loop_2_proc_U0_start_full_n = ap_const_logic_1;
}

void myproject_axi::thread_Loop_2_proc_U0_start_write() {
    Loop_2_proc_U0_start_write = ap_const_logic_0;
}

void myproject_axi::thread_ap_channel_done_is_last_0_i_loc_channel() {
    ap_channel_done_is_last_0_i_loc_channel = Loop_1_proc225_U0_ap_done.read();
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_0() {
    ap_channel_done_tmp_data_V_0 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_0.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_1() {
    ap_channel_done_tmp_data_V_1 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_1.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_2() {
    ap_channel_done_tmp_data_V_2 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_2.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_3() {
    ap_channel_done_tmp_data_V_3 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_3.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_4() {
    ap_channel_done_tmp_data_V_4 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_4.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_5() {
    ap_channel_done_tmp_data_V_5 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_5.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_6() {
    ap_channel_done_tmp_data_V_6 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_6.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_7() {
    ap_channel_done_tmp_data_V_7 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_7.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_8() {
    ap_channel_done_tmp_data_V_8 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_8.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_channel_done_tmp_data_V_9() {
    ap_channel_done_tmp_data_V_9 = (Block_myproject_axi_exit52_proc_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_data_V_9.read() ^ 
  ap_const_logic_1));
}

void myproject_axi::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_0() {
    ap_sync_channel_write_tmp_data_V_0 = ((ap_channel_done_tmp_data_V_0.read() & 
  tmp_data_V_0_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_0.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_1() {
    ap_sync_channel_write_tmp_data_V_1 = ((ap_channel_done_tmp_data_V_1.read() & 
  tmp_data_V_1_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_1.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_2() {
    ap_sync_channel_write_tmp_data_V_2 = ((ap_channel_done_tmp_data_V_2.read() & 
  tmp_data_V_2_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_2.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_3() {
    ap_sync_channel_write_tmp_data_V_3 = ((ap_channel_done_tmp_data_V_3.read() & 
  tmp_data_V_3_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_3.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_4() {
    ap_sync_channel_write_tmp_data_V_4 = ((ap_channel_done_tmp_data_V_4.read() & 
  tmp_data_V_4_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_4.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_5() {
    ap_sync_channel_write_tmp_data_V_5 = ((ap_channel_done_tmp_data_V_5.read() & 
  tmp_data_V_5_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_5.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_6() {
    ap_sync_channel_write_tmp_data_V_6 = ((ap_channel_done_tmp_data_V_6.read() & 
  tmp_data_V_6_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_6.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_7() {
    ap_sync_channel_write_tmp_data_V_7 = ((ap_channel_done_tmp_data_V_7.read() & 
  tmp_data_V_7_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_7.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_8() {
    ap_sync_channel_write_tmp_data_V_8 = ((ap_channel_done_tmp_data_V_8.read() & 
  tmp_data_V_8_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_8.read());
}

void myproject_axi::thread_ap_sync_channel_write_tmp_data_V_9() {
    ap_sync_channel_write_tmp_data_V_9 = ((ap_channel_done_tmp_data_V_9.read() & 
  tmp_data_V_9_full_n.read()) | ap_sync_reg_channel_write_tmp_data_V_9.read());
}

void myproject_axi::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void myproject_axi::thread_in_r_TREADY() {
    in_r_TREADY = Loop_1_proc225_U0_in_r_TREADY.read();
}

void myproject_axi::thread_myproject_U0_ap_continue() {
    myproject_U0_ap_continue = ap_const_logic_1;
}

void myproject_axi::thread_myproject_U0_ap_start() {
    myproject_U0_ap_start = start_for_myproject_U0_empty_n.read();
}

void myproject_axi::thread_out_r_TDATA() {
    out_r_TDATA = Loop_2_proc_U0_out_r_TDATA.read();
}

void myproject_axi::thread_out_r_TLAST() {
    out_r_TLAST = Loop_2_proc_U0_out_r_TLAST.read();
}

void myproject_axi::thread_out_r_TVALID() {
    out_r_TVALID = Loop_2_proc_U0_out_r_TVALID.read();
}

void myproject_axi::thread_start_for_Block_myproject_axi_exit52_proc_U0_din() {
    start_for_Block_myproject_axi_exit52_proc_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void myproject_axi::thread_start_for_myproject_U0_din() {
    start_for_myproject_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void myproject_axi::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"in_r_TDATA\" :  \"" << in_r_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TLAST\" :  \"" << in_r_TLAST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"out_r_TDATA\" :  \"" << out_r_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TLAST\" :  \"" << out_r_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"in_r_TVALID\" :  \"" << in_r_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"in_r_TREADY\" :  \"" << in_r_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"out_r_TVALID\" :  \"" << out_r_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"out_r_TREADY\" :  \"" << out_r_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

