// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "zeropad2d_cl_array_array_ap_ufixed_3u_config14_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_ST_fsm_state1 = "1";
const sc_lv<3> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_ST_fsm_state2 = "10";
const sc_lv<3> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_ST_fsm_state3 = "100";
const sc_lv<32> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_lv32_2 = "10";
const sc_lv<1> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_lv1_0 = "0";
const sc_lv<32> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_lv32_1 = "1";
const sc_lv<6> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_lv6_0 = "000000";
const sc_lv<1> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_lv1_1 = "1";
const sc_lv<6> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_lv6_20 = "100000";
const sc_lv<6> zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_lv6_1 = "1";
const bool zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::ap_const_boolean_1 = true;

zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::zeropad2d_cl_array_array_ap_ufixed_3u_config14_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state3);
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln61_fu_93_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_data_V_data_0_V_blk_n);
    sensitive << ( data_V_data_0_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );

    SC_METHOD(thread_data_V_data_0_V_read);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_data_V_data_1_V_blk_n);
    sensitive << ( data_V_data_1_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );

    SC_METHOD(thread_data_V_data_1_V_read);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_data_V_data_2_V_blk_n);
    sensitive << ( data_V_data_2_V_empty_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );

    SC_METHOD(thread_data_V_data_2_V_read);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_i_fu_99_p2);
    sensitive << ( i1_0_reg_71 );

    SC_METHOD(thread_icmp_ln61_fu_93_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i1_0_reg_71 );

    SC_METHOD(thread_icmp_ln65_fu_105_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );
    sensitive << ( j3_0_reg_82 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln61_fu_93_p2 );

    SC_METHOD(thread_io_acc_block_signal_op26);
    sensitive << ( data_V_data_0_V_empty_n );
    sensitive << ( data_V_data_1_V_empty_n );
    sensitive << ( data_V_data_2_V_empty_n );

    SC_METHOD(thread_io_acc_block_signal_op30);
    sensitive << ( res_V_data_0_V_full_n );
    sensitive << ( res_V_data_1_V_full_n );
    sensitive << ( res_V_data_2_V_full_n );

    SC_METHOD(thread_j_fu_111_p2);
    sensitive << ( j3_0_reg_82 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_V_data_0_V_blk_n);
    sensitive << ( res_V_data_0_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );

    SC_METHOD(thread_res_V_data_0_V_din);
    sensitive << ( data_V_data_0_V_dout );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_res_V_data_0_V_write);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_res_V_data_1_V_blk_n);
    sensitive << ( res_V_data_1_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );

    SC_METHOD(thread_res_V_data_1_V_din);
    sensitive << ( data_V_data_1_V_dout );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_res_V_data_1_V_write);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_res_V_data_2_V_blk_n);
    sensitive << ( res_V_data_2_V_full_n );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );

    SC_METHOD(thread_res_V_data_2_V_din);
    sensitive << ( data_V_data_2_V_dout );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_res_V_data_2_V_write);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln65_fu_105_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( io_acc_block_signal_op26 );
    sensitive << ( io_acc_block_signal_op30 );
    sensitive << ( icmp_ln61_fu_93_p2 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "zeropad2d_cl_array_array_ap_ufixed_3u_config14_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, data_V_data_0_V_dout, "(port)data_V_data_0_V_dout");
    sc_trace(mVcdFile, data_V_data_0_V_empty_n, "(port)data_V_data_0_V_empty_n");
    sc_trace(mVcdFile, data_V_data_0_V_read, "(port)data_V_data_0_V_read");
    sc_trace(mVcdFile, data_V_data_1_V_dout, "(port)data_V_data_1_V_dout");
    sc_trace(mVcdFile, data_V_data_1_V_empty_n, "(port)data_V_data_1_V_empty_n");
    sc_trace(mVcdFile, data_V_data_1_V_read, "(port)data_V_data_1_V_read");
    sc_trace(mVcdFile, data_V_data_2_V_dout, "(port)data_V_data_2_V_dout");
    sc_trace(mVcdFile, data_V_data_2_V_empty_n, "(port)data_V_data_2_V_empty_n");
    sc_trace(mVcdFile, data_V_data_2_V_read, "(port)data_V_data_2_V_read");
    sc_trace(mVcdFile, res_V_data_0_V_din, "(port)res_V_data_0_V_din");
    sc_trace(mVcdFile, res_V_data_0_V_full_n, "(port)res_V_data_0_V_full_n");
    sc_trace(mVcdFile, res_V_data_0_V_write, "(port)res_V_data_0_V_write");
    sc_trace(mVcdFile, res_V_data_1_V_din, "(port)res_V_data_1_V_din");
    sc_trace(mVcdFile, res_V_data_1_V_full_n, "(port)res_V_data_1_V_full_n");
    sc_trace(mVcdFile, res_V_data_1_V_write, "(port)res_V_data_1_V_write");
    sc_trace(mVcdFile, res_V_data_2_V_din, "(port)res_V_data_2_V_din");
    sc_trace(mVcdFile, res_V_data_2_V_full_n, "(port)res_V_data_2_V_full_n");
    sc_trace(mVcdFile, res_V_data_2_V_write, "(port)res_V_data_2_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, data_V_data_0_V_blk_n, "data_V_data_0_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln65_fu_105_p2, "icmp_ln65_fu_105_p2");
    sc_trace(mVcdFile, data_V_data_1_V_blk_n, "data_V_data_1_V_blk_n");
    sc_trace(mVcdFile, data_V_data_2_V_blk_n, "data_V_data_2_V_blk_n");
    sc_trace(mVcdFile, res_V_data_0_V_blk_n, "res_V_data_0_V_blk_n");
    sc_trace(mVcdFile, res_V_data_1_V_blk_n, "res_V_data_1_V_blk_n");
    sc_trace(mVcdFile, res_V_data_2_V_blk_n, "res_V_data_2_V_blk_n");
    sc_trace(mVcdFile, i_fu_99_p2, "i_fu_99_p2");
    sc_trace(mVcdFile, i_reg_135, "i_reg_135");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, j_fu_111_p2, "j_fu_111_p2");
    sc_trace(mVcdFile, io_acc_block_signal_op26, "io_acc_block_signal_op26");
    sc_trace(mVcdFile, io_acc_block_signal_op30, "io_acc_block_signal_op30");
    sc_trace(mVcdFile, ap_block_state3, "ap_block_state3");
    sc_trace(mVcdFile, i1_0_reg_71, "i1_0_reg_71");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, j3_0_reg_82, "j3_0_reg_82");
    sc_trace(mVcdFile, icmp_ln61_fu_93_p2, "icmp_ln61_fu_93_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::~zeropad2d_cl_array_array_ap_ufixed_3u_config14_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln61_fu_93_p2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_1))) {
        i1_0_reg_71 = i_reg_135.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i1_0_reg_71 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))))) {
        j3_0_reg_82 = j_fu_111_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln61_fu_93_p2.read()))) {
        j3_0_reg_82 = ap_const_lv6_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_135 = i_fu_99_p2.read();
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_block_state3() {
    ap_block_state3 = ((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read())));
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln61_fu_93_p2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_data_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0))) {
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n.read();
    } else {
        data_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_data_V_data_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))))) {
        data_V_data_0_V_read = ap_const_logic_1;
    } else {
        data_V_data_0_V_read = ap_const_logic_0;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_data_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0))) {
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n.read();
    } else {
        data_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_data_V_data_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))))) {
        data_V_data_1_V_read = ap_const_logic_1;
    } else {
        data_V_data_1_V_read = ap_const_logic_0;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_data_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0))) {
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n.read();
    } else {
        data_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_data_V_data_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))))) {
        data_V_data_2_V_read = ap_const_logic_1;
    } else {
        data_V_data_2_V_read = ap_const_logic_0;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_i_fu_99_p2() {
    i_fu_99_p2 = (!i1_0_reg_71.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(i1_0_reg_71.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_icmp_ln61_fu_93_p2() {
    icmp_ln61_fu_93_p2 = (!i1_0_reg_71.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_71.read() == ap_const_lv6_20);
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_icmp_ln65_fu_105_p2() {
    icmp_ln65_fu_105_p2 = (!j3_0_reg_82.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(j3_0_reg_82.read() == ap_const_lv6_20);
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln61_fu_93_p2.read()))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_io_acc_block_signal_op26() {
    io_acc_block_signal_op26 = (data_V_data_0_V_empty_n.read() & data_V_data_1_V_empty_n.read() & data_V_data_2_V_empty_n.read());
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_io_acc_block_signal_op30() {
    io_acc_block_signal_op30 = (res_V_data_0_V_full_n.read() & res_V_data_1_V_full_n.read() & res_V_data_2_V_full_n.read());
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_j_fu_111_p2() {
    j_fu_111_p2 = (!j3_0_reg_82.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j3_0_reg_82.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_res_V_data_0_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0))) {
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n.read();
    } else {
        res_V_data_0_V_blk_n = ap_const_logic_1;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_res_V_data_0_V_din() {
    res_V_data_0_V_din = data_V_data_0_V_dout.read();
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_res_V_data_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))))) {
        res_V_data_0_V_write = ap_const_logic_1;
    } else {
        res_V_data_0_V_write = ap_const_logic_0;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_res_V_data_1_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0))) {
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n.read();
    } else {
        res_V_data_1_V_blk_n = ap_const_logic_1;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_res_V_data_1_V_din() {
    res_V_data_1_V_din = data_V_data_1_V_dout.read();
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_res_V_data_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))))) {
        res_V_data_1_V_write = ap_const_logic_1;
    } else {
        res_V_data_1_V_write = ap_const_logic_0;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_res_V_data_2_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0))) {
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n.read();
    } else {
        res_V_data_2_V_blk_n = ap_const_logic_1;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_res_V_data_2_V_din() {
    res_V_data_2_V_din = data_V_data_2_V_dout.read();
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_res_V_data_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
         !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))))) {
        res_V_data_2_V_write = ap_const_logic_1;
    } else {
        res_V_data_2_V_write = ap_const_logic_0;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_start_out() {
    start_out = real_start.read();
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void zeropad2d_cl_array_array_ap_ufixed_3u_config14_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln61_fu_93_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))) && esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && !((esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op26.read())) || (esl_seteq<1,1,1>(icmp_ln65_fu_105_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, io_acc_block_signal_op30.read()))))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

