-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity zeropad2d_cl_array_array_ap_ufixed_3u_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    data_V_data_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    data_V_data_0_V_empty_n : IN STD_LOGIC;
    data_V_data_0_V_read : OUT STD_LOGIC;
    data_V_data_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    data_V_data_1_V_empty_n : IN STD_LOGIC;
    data_V_data_1_V_read : OUT STD_LOGIC;
    data_V_data_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    data_V_data_2_V_empty_n : IN STD_LOGIC;
    data_V_data_2_V_read : OUT STD_LOGIC;
    res_V_data_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_0_V_full_n : IN STD_LOGIC;
    res_V_data_0_V_write : OUT STD_LOGIC;
    res_V_data_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_1_V_full_n : IN STD_LOGIC;
    res_V_data_1_V_write : OUT STD_LOGIC;
    res_V_data_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    res_V_data_2_V_full_n : IN STD_LOGIC;
    res_V_data_2_V_write : OUT STD_LOGIC );
end;


architecture behav of zeropad2d_cl_array_array_ap_ufixed_3u_config14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal data_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln65_fu_105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_V_data_1_V_blk_n : STD_LOGIC;
    signal data_V_data_2_V_blk_n : STD_LOGIC;
    signal res_V_data_0_V_blk_n : STD_LOGIC;
    signal res_V_data_1_V_blk_n : STD_LOGIC;
    signal res_V_data_2_V_blk_n : STD_LOGIC;
    signal i_fu_99_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal i_reg_135 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal j_fu_111_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal io_acc_block_signal_op26 : STD_LOGIC;
    signal io_acc_block_signal_op30 : STD_LOGIC;
    signal ap_block_state3 : BOOLEAN;
    signal i1_0_reg_71 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal j3_0_reg_82 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln61_fu_93_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln61_fu_93_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i1_0_reg_71_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i1_0_reg_71 <= i_reg_135;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i1_0_reg_71 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    j3_0_reg_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                j3_0_reg_82 <= j_fu_111_p2;
            elsif (((icmp_ln61_fu_93_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j3_0_reg_82 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_135 <= i_fu_99_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln65_fu_105_p2, ap_CS_fsm_state2, io_acc_block_signal_op26, io_acc_block_signal_op30, icmp_ln61_fu_93_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln61_fu_93_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state3_assign_proc : process(icmp_ln65_fu_105_p2, io_acc_block_signal_op26, io_acc_block_signal_op30)
    begin
                ap_block_state3 <= (((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln61_fu_93_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln61_fu_93_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    data_V_data_0_V_blk_n_assign_proc : process(data_V_data_0_V_empty_n, ap_CS_fsm_state3, icmp_ln65_fu_105_p2)
    begin
        if (((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_V_data_0_V_blk_n <= data_V_data_0_V_empty_n;
        else 
            data_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_0_V_read_assign_proc : process(ap_CS_fsm_state3, icmp_ln65_fu_105_p2, io_acc_block_signal_op26, io_acc_block_signal_op30)
    begin
        if ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_V_data_0_V_read <= ap_const_logic_1;
        else 
            data_V_data_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_1_V_blk_n_assign_proc : process(data_V_data_1_V_empty_n, ap_CS_fsm_state3, icmp_ln65_fu_105_p2)
    begin
        if (((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_V_data_1_V_blk_n <= data_V_data_1_V_empty_n;
        else 
            data_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_1_V_read_assign_proc : process(ap_CS_fsm_state3, icmp_ln65_fu_105_p2, io_acc_block_signal_op26, io_acc_block_signal_op30)
    begin
        if ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_V_data_1_V_read <= ap_const_logic_1;
        else 
            data_V_data_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_2_V_blk_n_assign_proc : process(data_V_data_2_V_empty_n, ap_CS_fsm_state3, icmp_ln65_fu_105_p2)
    begin
        if (((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_V_data_2_V_blk_n <= data_V_data_2_V_empty_n;
        else 
            data_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_2_V_read_assign_proc : process(ap_CS_fsm_state3, icmp_ln65_fu_105_p2, io_acc_block_signal_op26, io_acc_block_signal_op30)
    begin
        if ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            data_V_data_2_V_read <= ap_const_logic_1;
        else 
            data_V_data_2_V_read <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_99_p2 <= std_logic_vector(unsigned(i1_0_reg_71) + unsigned(ap_const_lv6_1));
    icmp_ln61_fu_93_p2 <= "1" when (i1_0_reg_71 = ap_const_lv6_20) else "0";
    icmp_ln65_fu_105_p2 <= "1" when (j3_0_reg_82 = ap_const_lv6_20) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln61_fu_93_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln61_fu_93_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    io_acc_block_signal_op26 <= (data_V_data_2_V_empty_n and data_V_data_1_V_empty_n and data_V_data_0_V_empty_n);
    io_acc_block_signal_op30 <= (res_V_data_2_V_full_n and res_V_data_1_V_full_n and res_V_data_0_V_full_n);
    j_fu_111_p2 <= std_logic_vector(unsigned(j3_0_reg_82) + unsigned(ap_const_lv6_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    res_V_data_0_V_blk_n_assign_proc : process(res_V_data_0_V_full_n, ap_CS_fsm_state3, icmp_ln65_fu_105_p2)
    begin
        if (((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            res_V_data_0_V_blk_n <= res_V_data_0_V_full_n;
        else 
            res_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_0_V_din <= data_V_data_0_V_dout;

    res_V_data_0_V_write_assign_proc : process(ap_CS_fsm_state3, icmp_ln65_fu_105_p2, io_acc_block_signal_op26, io_acc_block_signal_op30)
    begin
        if ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            res_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_1_V_blk_n_assign_proc : process(res_V_data_1_V_full_n, ap_CS_fsm_state3, icmp_ln65_fu_105_p2)
    begin
        if (((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            res_V_data_1_V_blk_n <= res_V_data_1_V_full_n;
        else 
            res_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_1_V_din <= data_V_data_1_V_dout;

    res_V_data_1_V_write_assign_proc : process(ap_CS_fsm_state3, icmp_ln65_fu_105_p2, io_acc_block_signal_op26, io_acc_block_signal_op30)
    begin
        if ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            res_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_2_V_blk_n_assign_proc : process(res_V_data_2_V_full_n, ap_CS_fsm_state3, icmp_ln65_fu_105_p2)
    begin
        if (((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            res_V_data_2_V_blk_n <= res_V_data_2_V_full_n;
        else 
            res_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_2_V_din <= data_V_data_2_V_dout;

    res_V_data_2_V_write_assign_proc : process(ap_CS_fsm_state3, icmp_ln65_fu_105_p2, io_acc_block_signal_op26, io_acc_block_signal_op30)
    begin
        if ((not((((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op30 = ap_const_logic_0)) or ((icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (io_acc_block_signal_op26 = ap_const_logic_0)))) and (icmp_ln65_fu_105_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            res_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
